### DISCUSSION TITLE
create package from private repository

### DISCUSSION THREAD

**Discussion by jichu20** [fission/fission#3206] [General]
Hello.

I was trying to generate a package from a private repository. I tried using https://${username}:${password}@xxxxxx/xxx.zip, but I'm having login issues. Instead, if I use the username and password directly, it allows me to download the zip and generate the package.

I have the package defined as follows:

```yaml
--- 
apiVersion: fission.io/v1
kind: Package
metadata:
  name: pck-proxy
  namespace: default
spec:
  deployment:
    type: empty
  environment:
    name: python
    namespace: default
  source:
    type: url
    url: https://${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}@artifactory/artifactory/fission/demo-src-pkg.zip
```

I have the env defined as follows:

```yaml
spec:
  builder:
    command: build
    image: artifactory/fission/python-builder  
    container:
      name: builder
      resources: {}
      env:
        - name: ARTIFACTORY_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-artifactory
              key: username
        - name: ARTIFACTORY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-artifactory
              key: password
    podspec:
      containers:
      - name: builder
        resources: {}
      - name: fetcher
        resources: {}
        env:
          - name: ARTIFACTORY_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-artifactory
                key: username
          - name: ARTIFACTORY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-artifactory
                key: password
```
I hope you can help me.
