### ISSUE TITLE
Unable to update value of route(http trigger)

### ISSUE THREAD

**Issue by life1347** [fission/fission#1074]
bug: update the value of a route and prompt following error message.
```
$ fission route list
NAME                                 METHOD  HOST URL                           INGRESS FUNCTION_NAME
fe05f24c-2b4d-4880-8f2c-aadaca9bdbf3 GET          /echo                         false   dt1

$ fission route update --name fe05f24c-2b4d-4880-8f2c-aadaca9bdbf3 --function dt2
Fatal error: Failed to update HTTP trigger: Resource exists - HTTPTrigger with same Host, URL & method already exists (fe05f24c-2b4d-4880-8f2c-aadaca9bdbf3)
```

**Comment by holyketzer** [comment]
Is it supposed to be fixed? I Faced it recently: 

```
goroutine 1646729 [running]:
runtime/debug.Stack(0xed5172e5d, 0x2382560, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/fission/fission/pkg/controller.(*API).respondWithError(0xc00019b030, 0x17e94e0, 0xc00083ed20, 0x17d1cc0, 0xc0006e3480)
	/go/src/github.com/fission/fission/pkg/controller/api.go:114 +0x34
github.com/fission/fission/pkg/controller.(*API).HTTPTriggerApiCreate(0xc00019b030, 0x17e94e0, 0xc00083ed20, 0xc0007fa400)
	/go/src/github.com/fission/fission/pkg/controller/httpTriggerApi.go:90 +0x40e
github.com/fission/fission/pkg/controller.(*API).HTTPTriggerApiCreate-fm(0x17e94e0, 0xc00083ed20, 0xc0007fa400)
	/go/src/github.com/fission/fission/pkg/controller/api.go:216 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0002ebc20, 0x17e94e0, 0xc00083ed20, 0xc0007fa400)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000165d40, 0x17e94e0, 0xc00083ed20, 0xc00092c000)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xd0
net/http.serverHandler.ServeHTTP(0xc00049e000, 0x17e94e0, 0xc00083ed20, 0xc00092c000)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000829400, 0x17ecaa0, 0xc000077740)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
{"level":"error","ts":1569011687.862327,"logger":"controller.api","caller":"controller/api.go:124","msg":"HTTPTrigger with same Host, URL & method already exists (my-function-name)","code":409}
```

Curl response is:
```
< HTTP/1.1 404 Not Found
< Content-Type: text/html
< Date: Tue, 22 Oct 2019 08:24:44 GMT
< Server: openresty/1.15.8.1
< Content-Length: 159
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty/1.15.8.1</center>
</body>
</html>
```

```
$ fission -v                                                                                                                                                                 
client:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
server:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
```

**Comment by life1347** [comment]
I think it's a different problem. There are a couple things worth to take a look
1. Is there a http trigger with the same host/URL/method exists?
2. If yes, and the http trigger is not created by `fission spec`, then it's an expected error. Because fission spec won't override the existing resource if it's not created by spec.
3. If yes and the http trigger is created by `fission spec (applying fission spec)` , then it's a fission spec bug.
4. If no, it's an unknown issue.

For 3, 4 could you share the spec you tested against with? so that we can try to reproduce the problem.

**Comment by holyketzer** [comment]
Thank you for the response:
Trigger is existed before and it's declared in spec.

Our spec looks like this:
```
---
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: our-project-python
  namespace: fission
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::<id>:role/<name>
spec:
  TerminationGracePeriod: 90
  builder:
    command: build
    image: fission/python-builder:latest
  keeparchive: false
  poolsize: 2
  resources: {}
  runtime:
    functionendpointport: 0
    image: our-image
    loadendpointpath: ""
    loadendpointport: 0
    podspec:
      nodeSelector:
        role: functions
  version: 3
---
# This file is generated by the 'fission spec init' command.
# See the README in this directory for background and usage information.
# Do not edit the UID below: that will break 'fission spec apply'
apiVersion: fv1.io/v1
kind: DeploymentConfig
name: fission-specs
uid: 75438cbe-65a0-4dc7-ba6a-5715973c57ac
---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: our-function
  namespace: fission-function
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps:
  - name: our-configmap
    namespace: fission-function
  environment:
    name: our-project-python
    namespace: fission
  package:
    functionName: project_functions.our-function.main
    packageref:
      name: efoi
      namespace: fission-function
  resources: {}
  secrets:
  - name: our-secret
    namespace: fission-function
---
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: our-function
  namespace: fission-function
spec:
  createingress: true
  functionref:
    functionweights: null
    name: our-function
    type: name
  host: our-host
  method: POST
  relativeurl: /our-function
```
