### ISSUE TITLE
Installing on Docker Desktop instead of minikube / problems with full install

### ISSUE THREAD

**Issue by andreialecu** [fission/fission#1107]
Docker now has Kubernetes built in. There are various CPU usage issues with minikube so I'm trying to use the built in Docker way to install fission.

I'm running this on Windows fwiw.

I was able to install the "minimal" package successfully via `helm`, but I'm not able to see function logs with it - I assume because of the missing `influxdb`.

Installing the `full` package results in the fission cli returning errors such as:

```
$ fission spec apply --wait
Fatal error: Error forwarding to controller port: error upgrading connection: the server does not allow this method on the requested resource
```
`kubectl get po --all-namespaces` shows this:

![image](https://user-images.githubusercontent.com/697707/53287026-2acd9080-377f-11e9-8701-47d15e27770e.png)

I notice that the controller shows ready `0/1`.

**With the minimal setup the controller starts properly and fission connects to it.**

On minikube, the full version works as well. It's just on Docker Desktop's kubernetes that I see these problems.

Also tried with both `helm` and the `kubectl apply` methods.

Alternatively, is there a way to get logging to work on the minimal install?

**Comment by andreialecu** [comment]
Upon further investigation I see that the difference in configuration for the controller between `fission-all` and `fission-minimal` is this in `config.yaml`:

fission-all:
```yaml
canary:
  enabled: true
  prometheusSvc: "http://fission-1-0-0-prometheus-server.default"
```

The minimal version doesn't use prometheus. Based on my screenshot above, I also notice that `prometheus-server` and `prometheus-alertmanager` isn't ready, so this must be why the controller keeps crashing.

Possibly related to: https://github.com/fission/fission/issues/618

**Comment by andreialecu** [comment]
I was able to solve the problem. It was caused by the fact that the `PersistentVolumeClaims` were stuck on pending because there were no `PersistentVolumes` available.

I got it to work by manually creating 3 PVs like this:

pv-volume.yaml:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/pvc1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/pvc2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
spec:
  capacity:
    storage: 10Gi
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/pvc3
```

Then run `kubectl create -f pv-volume.yaml`. All the pods should then successfully start.

I'm a beginner with kubernetes so the yaml above may not be optimal, but at least it works now.
