### ISSUE TITLE
Update GO docs/getting started to use go-env-1.12 

### ISSUE THREAD

**Issue by Guyzeroth** [fission/fission#1261]
```
fission --version
client:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
server:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
```

Following the GO docs for using fission spec init , etc . Using the env + builder images 

` fission environment create --name go --image fission/go-env --builder fission/go-builder`

This lead to  `go mod init\ngo: unknown subcommand \"mod\"\nRun 'go help' for usage.\n` error messages when doing `fission spec apply ` 

Fixed by updating env to use the undocumented go 1.12 images 

`fission env create --name go --image fission/go-env-1.12:1.4.1 --builder fission/go-builder:1.4.1`
