### ISSUE TITLE
Update Installing Fission/Run an example docs to use go-env-1.12

### ISSUE THREAD

**Issue by podoplelova** [fission/fission#1274]
**Fission/Kubernetes version**

```
fission --version
client:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
server:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
```

**Describe the bug**
Following the docs in `Installing Fission` -> [`Run an example`](https://docs.fission.io/installation/#run-an-example) leads to an error in the builder logs:

```
+ '[' -f go.mod ']'
+ go mod init
go: unknown subcommand "mod"
Run 'go help' for usage.
+ rm -rf /usr/src/hello-go-9i8l-uui3po
error waiting for cmd "build": exit status 2
```

Fixed by using `fission env create --name go --image fission/go-env-1.12:1.4.1 --builder fission/go-builder-1.12:1.4.1` (same issue as #1261, different spot in the docs).
