### ISSUE TITLE
Ruby function shows 502

### ISSUE THREAD

**Issue by life1347** [fission/fission#1277]
From @mkanoor (https://github.com/fission/fission/pull/1101#issuecomment-522602312)
I am using
```
client:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
server:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
```
On a Mac with docker desktop and Kubernetes (v.1.14.3)

I download the sample code from the repo

```
fission function create --name parse --env ruby --src "parse/*" --entrypoint handler 
Package 'sumd' created
function 'parse' created
fission fn test --name parse --body '<message>This is my message</message>'
Error calling function parse: 502; Please try again or fix the error:
```

Question: Is --src option broken for ruby?
