### ISSUE TITLE
Fission route URL param doesn't support encode string

### ISSUE THREAD

**Issue by wphowto** [fission/fission#1317]
Implemented fission route with this format `account/{name}`.

It works with following input:

`localhost:9090/account/andrew`

It doesn't work if there's encoded url string, it doesn't fire the function, the route seems to ignore url params with encoded string.

`localhost:9090/account/simon%2Freal`

Is encoded url supported for URL params?

**Comment by life1347** [comment]
Hi @wphowto , what version you tested with? And did you use `"` to quote the URL when creating the http trigger?

```
$ fission route create --name h3 --method GET --function h1 --url "/k/{asd}"
trigger 'h3' created

$ curl http://192.168.99.100:31314/k%2Freal
hello, world!

$ curl http://192.168.99.100:31314/k/real
hello, world!
```

**Comment by wphowto** [comment]
Hi @life1347 , I am using fission 1.5.0, tried with what you suggest. Didn't work for me.

`fission route create --spec --method GET --url "/dummy/{url}" --function dummy`

```
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 1563aa19-c4bc-43d5-802b-fbf57968fb72
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: dummy
    type: name
  method: GET
  relativeurl: "/dummy/{url}"
```
