### ISSUE TITLE
Issue declaring imagePullPolicy with pool manager podspec

### ISSUE THREAD

**Issue by holyketzer** [fission/fission#1322]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
server:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

AWS EKS

**Describe the bug**

I'm following https://blog.fission.io/posts/fission_pod_specs/ but Fission doesn't apply `podspec` `containers` patch to actual deployment, i try to change `imagePullPolicy` and add env var, after `fission apply` deployment is restarted but still has no env vars and `imagePullPolicy: IfNotPresent`.

**To Reproduce**

```
---
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: my-python-env
  namespace: fission
spec:
  TerminationGracePeriod: 90
  builder:
    command: build
    image: fission/python-builder:latest
  keeparchive: false
  poolsize: {{ poolsize }}
  resources: {}
  runtime:
    functionendpointport: 0
    image: my-custom-python-image
    loadendpointpath: ""
    loadendpointport: 0
    podspec:
      nodeSelector:
        role: functions
      containers:
        - name: my-python-env
          image: my-custom-python-image
          imagePullPolicy: Always
          env:
            - name: SOME_NAME
              value: some_value
  version: 3
```

**Expected result**

I expect that container for `my-custom-python-image` inside `poolmgr-my-python-env-fission` deployment will have `imagePullPolicy: Always` and my env var

**Actual result**

It has no env vars and `imagePullPolicy: IfNotPresent`
