### ISSUE TITLE
Ingress for route is missing host

### ISSUE THREAD

**Issue by knobotz** [fission/fission#1323]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2019-09-09T05:27:10Z"
    GitCommit: d2d0467375d3318000ca57599c80691c8471a0a1
    Version: 1.5.0
server:
  fission/core:
    BuildDate: "2019-09-09T05:27:10Z"
    GitCommit: d2d0467375d3318000ca57599c80691c8471a0a1
    Version: 1.5.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
EKS

**Describe the bug**

It appears that using specs or the fission cli to create a route with 1.5.0 is no longer setting the host. 

**To Reproduce**
Use the following route spec:

```yaml
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: hello
  namespace: fission-function
spec:
  createingress: true
  functionref:
    functionweights: null
    name: hello
    type: name
  host: myhost.com
  method: POST
  relativeurl: /hello
```

**Expected result**

Ingress should be created with host set to "myhost.com"

**Actual result**
Ingress is created with "*" host:

```sh
$ kubectl get ingress -n fission
NAME     HOSTS     ADDRESS                                PORTS   AGE
hello    *         some-elb.us-east-1.elb.amazonaws.com   80      31h
```

The fission route is also incorrect:

```sh
$ fission route list --triggerns fission-function
NAME    METHOD HOST   URL      INGRESS FUNCTION_NAME
hello   POST   *      /hello   true    hello
```
**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

This same spec works in 1.4.1, correct host is set for the ingress objects.
