### ISSUE TITLE
HPA replicas keeps bouncing due to readiness probe

### ISSUE THREAD

**Issue by life1347** [fission/fission#1427]
User feedback that the replicas of HPA keep bouncing.
![image (3)](https://user-images.githubusercontent.com/202578/69347566-ac6f3200-0caf-11ea-8820-6d7c88e5eead.png)

The root cause of the problem is, the application requires long `initialDelaySeconds` for readiness probe. Currently, the value of `initialDelaySeconds` is `1` which is too strict for most of the application.

```
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /readiness-healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
```

Consider the [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes) is added in 1.16 and is not supported in most of kubernetes version. We need to figure another way to solve the problem.

ref: https://github.com/kubernetes/kubernetes/issues/51650#issuecomment-327572089
