### ISSUE TITLE
Builder manager failed to merge podspec due to name conflict

### ISSUE THREAD

**Issue by life1347** [fission/fission#1459]
**Fission/Kubernetes version**

master branch

<pre>
$ fission --version
$ kubectl version
</pre>

**Describe the bug**

Builder manager failed to merge container due to name conflict while it works for executor.

```
{"level":"error","ts":1575623535.306294,"logger":"builder_manager.environment_watcher","caller":"buildermgr/envwatcher.go:205","msg":"error creating builder","error":"error creating builder deployment: Deployment.apps \"nodejs-2917587\" is invalid: [spec.template.spec.containers[1].image: Required value, spec.template.spec.containers[2].name: Duplicate value: \"fetcher\"]","errorVerbose":"Deployment.apps \"nodejs-2917587\" is invalid: [spec.template.spec.containers[1].image: Required value, spec.template.spec.containers[2].name: Duplicate value: \"fetcher\"]\nerror creating builder deployment\ngithub.com/fission/fission/pkg/buildermgr.(*environmentWatcher).createBuilder\n\t/go/src/pkg/buildermgr/envwatcher.go:356\ngithub.com/fission/fission/pkg/buildermgr.(*environmentWatcher).service\n\t/go/src/pkg/buildermgr/envwatcher.go:230\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","builder_target":"nodejs"}
```

**To Reproduce**

```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: default
spec:
  builder:
    command: build
    image: fission/node-builder
    podspec:
      containers:
      - name: fetcher
        env:
        - name: LOG_LEVEL
          value: info
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    image: fission/node-env
    podspec:
      containers:
      - name: fetcher
        env:
        - name: LOG_LEVEL
          value: info
  version: 2
```
