### ISSUE TITLE
Enable support of git urls in Package definitions

### ISSUE THREAD

**Issue by anantkaushik1989** [fission/fission#1475]
https://docs.fission.io/docs/spec/

**Fission/Kubernetes version**

<pre>
$ fission --version
1.7.1
$ kubectl version
1.17.0
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
MiniKube on Ubuntu 18.04

**Describe the bug**
I have been following the Fission guide to understand the framework and its capabilities. During this, I was looking at Declarative Specs.

From the current specs for 'Package' resource, I see that the spec supports source with an archived url. Could we make this also support github links, so that we can allow simpler adoption for large code bases?

Example - 

```
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: calc-eval-fe9ceb5c-d4ec-40c6-b8cf-81c3cdb22534
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python-ev
    namespace: default
  source:
    checksum: {}
    type: url 
    url: <github url>
```

Please let me know if this is possible already, so that I can close the issue.
**To Reproduce**

This is a feature request.

**Expected result**

Above spec can be deployed using spec apply.
