### ISSUE TITLE
Improved spec scaffolding experience

### ISSUE THREAD

**Issue by svenvNL** [fission/fission#1574]
Writing a function takes a lot of steps. In the case of a Java function, a Maven project needs to be created and the dependencies need to be added. For other languages, there is a simular experience.

After writing the function, specs need to be generated. These include a Package, Function and a trigger. Names need to match in multiple places, so a lot could go wrong. Below is a basic example for a Java function with an ingress endpoint:

- `fission pkg create --env java --src ./functions/<name>/pom.xml --src ./functions/<name>/src --name <name> --spec`

- `fission fn create --name <name> --pkg <name> --env java --entrypoint <classname> --executortype newdeploy --minscale 1 --maxscale 1 --spec`

- `fission httptrigger create --url /<url> --method GET --function <name> --createingress --ingressrule *=/<url> --name <name> --spec`

A would like to propose a new command, `fission new`.  This command should in my opinion not comprehend all possible options, but the most used. Below is a proposal for the arguments

| Flag | Description |
|---|---|
| --name -n <name> | Name for the package, function and trigger |
| --entrypoint -e <entrypoint> | Function entrypoint, same as in `fn create` |
| --trigger -t <http, queue, timer> | Trigger type |
| --url -u <url> | httptrigger URL, only when the trigger is http |
| --ingress <url> | ingress URL, only when the trigger is http |
| --cron <pattern> | timmertrigger, only when the trigger is timer |
| --mqtype <nats/kafka> | Message queue type, only when the trigger is queue |
| --topic <topic> | Message queue topic, only when the trigger is queue |
| --environemt --env <environemt> | The environment the function needs to run in |

At this moment, I don't want to include code scafolding, this would be a topic on its own.

**Comment by vishal-biyani** [comment]
Hey @svenvNL - this is a great suggestion, thanks for filing the issue. This will definitely help a new person get started relatively easily.

**Comment by svenvNL** [comment]
@vishal-biyani I could write a first implementation this weekend. I am not familiar with Go, so I don't expect that it will be anywhere near finished. Is it best to do it in multiple PR's or one big PR?

**Comment by vishal-biyani** [comment]
Hey, @svenvNL Thanks - definitely welcome the contribution. Go is fairly easy to start off and please ask questions if you run into issues on Slack.

I would say start off with a small PR with prototype - for ex. first, develop only the UX/Commands, then add only function creation and then in another iteration add all other aspects. I think most of this change will be in Fission CLI so it has a relatively clearly defined boundary.

**Comment by adamkgray** [comment]
Has any work been done on this? I'll re-kickstart this endeavor if were still at step 0

**Comment by sahil-lakhwani** [comment]
There could also be an option, something like `--create-spec` instead of a new sub-command. Because the code already creates the spec, this way, we'll have to just output the generated spec in YAML.
When using this option, the spec won't actually be applied/installed in the cluster.

**Comment by vishal-biyani** [comment]
@adamkgray We are pretty much at steo 0. Please free free to take it up and let us know if you need any help along the way!

**Comment by kbbqiu** [comment]
As an extension/augmentation to this issue, I was hoping that we could deploy fission spec via helm or skaffold.

Reason:
- We've got ~100 lamdas that we are looking to possibly move into fission
- Current spec workflow would require us to duplicate a bunch of code when generating the CRD k8s objects

Current Strategy:
- Helm chart to generate fission specs
- CI/CD will run `helm template` and pass in values file to generate fission spec
- fission-cli to apply the generate spec file

e.g. sample values file
```
# values.yaml

deploymentConfig:
  name: test_lambda
  # generate a uid, e.g. uuidgen
  uid: E7D816FC-3493-430E-91AF-CD999ABDFF5A

package:
  name: test_lambda
  # must have a directory named test_lambda with a function inside
  path: test_lambda/*

# functions is a type of list(map) meaning that each package can be attributed
# to N number of lambdas, main difference being the functionName (handler)
functions:
  - name: test_lambda_one
    functionName: index.handler_one
    maxScale: 2 # default 2
    minScale: 0 # default 0
    # triggers: one or more of messageQueue, http, or time
    # trigger types are also list(map)
    triggers:
      messageQueue:
        - type: aws-sqs-queue
          topic: test_lambda
          respTopic: test_lambda_response
          errorTopic: test_lambda_error
          region: us-east-1
          queueURL: https://sqs.us-east-1.amazonaws.com/523887678637
          secret: fission-sqs-test
          minReplica: 0 # default 0
          maxReplica: 2 # default 2
          cooldownPeriod: 300 # default 300
          pollingInterval: 30 # default 30
  - name: test_lambda_two
    functionName: index.handler_two
    maxScale: 1
    minScale: 0
    triggers:
      http:
        - method: GET
          path: /test_lambda
      time:
        - cron: "@every 10m"


```

Pros: 
- We're able to version our fission specs via helm charts
- Fewer lines of code and repeated k8s objects

Cons:
- Still missing some essential features
  - `helm ls` - rolling back deployments 
  - `helm diff` - easy way to diff changes between deployments
  - in general, fission-cli is extremely slow. Even running fission version takes a couple of seconds. What is it doing in the background?
