### ISSUE TITLE
Can't access volume from function

### ISSUE THREAD

**Issue by jacobpiggin** [fission/fission#1588]
**Fission/Kubernetes version**

Kubernetes: 1.8
Fission: 1.8

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Minikube

**Describe the bug**

I am trying to mount volumes to Python and Java environments but receive FileNotFound errors when trying to access the files in the volume. This has happened when using PersistentVolume & PersistentVolumeClaim and with HostPath volume types.

I've checked the permissions of the files/directories on the MiniKube node and they are RWX by all. Minikube automatically mounts /c/Users from the host PC onto the Minikube node. I also SSH'ed into the Minikube node and confirmed that the data directory exists and contains a file index.txt as expected.

**To Reproduce**
Add the following to the end of env-java-spec.yaml:
```  
podspec: 
    containers: 
    - name: java-spec 
      image: fission/jvm-env 
      volumeMounts: 
        - name: myvol 
          mountPath: /data 
    volumes: 
    - name: myvol 
      hostPath:  
        path: /c/Users/Jacob/data 
```
The data directory contains a file index.txt. Open and read the file /data/index.txt from a function. This function prints out any text that it reads from the file.

**Expected result**
The function prints out the contents of index.txt.

**Actual result**
This does not produce any output and looking at the logs for the function I can see the File Not Found error.

**Screenshots/Dump file**

[fission-dump_1588237635.zip](https://github.com/fission/fission/files/4557431/fission-dump_1588237635.zip)

**Additional context**
The PersistentVolume was a mnt/data directory created within the Minikube node. I created an nginx node to test that the PVC and PV were functioning correctly. This was what I added to env-python-spec.yaml:
```
  podspec:
    containers:
    - name: nodep
      image: fission/python-env
      volumeMounts:
        - name: pv-storage
          mountPath: /data
    volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
```

**Comment by vishal-biyani** [comment]
Hey, @jacobpiggin Thanks for filing the issue. I will try to reproduce this, but just checking if you are on Windows host or Linux host?

**Comment by jacobpiggin** [comment]
@vishal-biyani I'm on a Windows host.

**Comment by wpf710** [comment]
I ran into the same issue  on Centos with k8s 1.16 +fission  1.8.0

PodSpec
```
[root@master podspec]# cat specs/env-python.yaml 
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: python
  namespace: default
spec:
  builder:
    command: build
    image: fission/python-builder:1.8.0
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    image: fission/python-env:1.8.0
  version: 2
  podspec:
    containers:
    - name: python-volume
      image: fission/python-env:1.8.0
      volumeMounts:
        - name: funcvol
          mountPath: /mnt
    volumes:
      - name: funcvol
        hostPath:
          path: /mnt/yrfs
          type: Directory   
```

and with a python function to call the `os.popen("df -h") `
```
Filesystem Size Used Available Use% Mounted on 
overlay 17.0G 11.2G 5.7G 66% / 
tmpfs 64.0M 0 64.0M 0% /dev 
tmpfs 3.9G 0 3.9G 0% /sys/fs/cgroup 
/dev/mapper/centos-root 17.0G 11.2G 5.7G 66% /userfunc 
/dev/mapper/centos-root 17.0G 11.2G 5.7G 66% /secrets 
/dev/mapper/centos-root 17.0G 11.2G 5.7G 66% /configs 
/dev/mapper/centos-root 17.0G 11.2G 5.7G 66% /dev/termination-log 
/dev/mapper/centos-root 17.0G 11.2G 5.7G 66% /etc/resolv.conf 
/dev/mapper/centos-root 17.0G 11.2G 5.7G 66% /etc/hostname 
/dev/mapper/centos-root 17.0G 11.2G 5.7G 66% /etc/hosts 
shm 64.0M 0 64.0M 0% /dev/shm tmpfs 3.9G 12.0K 3.9G 0% /var/run/secrets/kubernetes.io/serviceaccount 
tmpfs 3.9G 0 3.9G 0% /proc/acpi tmpfs 64.0M 0 64.0M 0% /proc/kcore 
tmpfs 64.0M 0 64.0M 0% /proc/keys tmpfs 64.0M 0 64.0M 0% /proc/timer_list 
tmpfs 64.0M 0 64.0M 0% /proc/timer_stats tmpfs 64.0M 0 64.0M 0% /proc/sched_debug 
tmpfs 3.9G 0 3.9G 0% /proc/scsi tmpfs 3.9G 0 3.9G 0% /sys/firmware 
```
no mount point .

**Comment by rajalokan** [comment]
Hello, I feel this is because of an invalid syntax in spec manifest. I feel syntax is at wrong indent. Here `podspec` is a direct descendent of spec, which is wrong. It should rather be within `spec.runtime.podspec`. So above example from @wpf710 will be something like below 
 
```
[root@master podspec]# cat specs/env-python.yaml 
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: python
  namespace: default
spec:
  builder:
    command: build
    image: fission/python-builder:1.8.0
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    image: fission/python-env:1.8.0
  version: 2
    podspec:
      containers:
      - name: python-volume
        image: fission/python-env:1.8.0
        volumeMounts:
          - name: funcvol
            mountPath: /mnt
      volumes:
      - name: funcvol
        hostPath:
          path: /mnt/yrfs
          type: Directory   
```

Reason for this confusion is wrong documentation at [podspec/volume](https://docs.fission.io/docs/spec/podspec/volume/) I believe. I've shared an example spec with correct syntax as a [Pull Request](https://github.com/fission/fission/pull/1591/files?file-filters%5B%5D=.yaml#diff-f72e09b467f561ebc7fb0d871b638d92R16) . 

If you can follow that example and retry. On confirmation of this fixing the issue, I will raise a PR for fix in documentation.
