### ISSUE TITLE
Service Account in PodSpec is Ignored

### ISSUE THREAD

**Issue by vijayansarathy** [fission/fission#1699]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2020-06-29T16:26:41Z"
    GitCommit: e85d77bbce719fb898084c0ddb4ba37b199bf667
    Version: 1.10.0
server:
  fission/core:
    BuildDate: "2020-06-29T16:26:41Z"
    GitCommit: e85d77bbce719fb898084c0ddb4ba37b199bf667
    Version: 1.10.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Amazon EKS, EKS.2, Kubernetes 1.17

**Describe the bug**
I am trying to run a Function under a specific ServiceAccount so that I may leverage ability in EKS to assign IAM roles to Service Accounts. The complete spec for the Environment looks as follows:

```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: default
spec:
  builder:
    command: build
    image: fission/node-builder:latest 
  imagepullsecret: ""
  keeparchive: false
  poolsize: 2
  resources:
    limits:
      cpu: 80m
      memory: 128Mi
    requests:
      cpu: 40m
      memory: 64Mi
  runtime:
    image: fission/node-env:latest
    podspec:
      serviceAccount: s3reader
      securityContext: {}
  version: 3
```
I have also made sure that the service account I am using is bound to the **secret-configmap-getter** and **package-getter-binding** ClusterRoles. But this setting seems to be ignored and the Pod is always running under the identity of the service account named **fission-fetcher**

**To Reproduce**
Use an Environment definition with a PodSpec as the one shown above and deploy a function.

**Expected result**
I would have expected the Pod to run under the identity of the service account **s3reader**.

**Actual result**
Pod always runs under the identity of service account **fission-fetcher.**

**Screenshots/Dump file**
Fission dump file is attached.
[fission-dump_1599076563.zip](https://github.com/fission/fission/files/5164640/fission-dump_1599076563.zip)

<pre>
$ fission support dump
</pre>

**Additional context**
