### ISSUE TITLE
Failed to create environment: unexpected end of JSON input

### ISSUE THREAD

**Issue by jonathan-kosgei** [fission/fission#177]
I've exported the following svc urls
```
jonathan@sc-test-cluster:~$ export FISSION_URL=http://10.91.98.28:31313
jonathan@sc-test-cluster:~$ export FISSION_ROUTER=10.91.98.28:31314
```

I'm on azure which doesn't support type Loadbalancer so I've customised the fission-cloud.yml file as follows
```
apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: fission
  labels:
    svc: router
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31314
  selector:
    svc: router

---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: fission
  labels:
    svc: controller
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 31313
  selector:
    svc: controller
```

I'm trying to use type `nodePort`. My node's ip is `10.91.98.28`.

I get the following error when trying to add an environment
```
Failed to create environment: unexpected end of JSON input
```
