### ISSUE TITLE
Fission 1.11.0 environment declarative specs are not working

### ISSUE THREAD

**Issue by abbaspw21** [fission/fission#1805]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2020-09-16T15:37:59Z"
    GitCommit: 09b4ffed78ad7a7eea7ebaf47e7644843b0a0b12
    Version: 1.11.0
server:
  fission/core:
    BuildDate: "2020-09-16T13:41:28Z"
    GitCommit: f034a1c734af51cdd6dd4449d1db253a67e699c3
    Version: 1.11.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

</pre>

**Describe the bug**
After Upgrading fission to **1.11.0 from 1.9.0** declarative specs for fission environment are not working as expected. The configurations present in specs template file for **resources**, **runtime.container** and **runtime.podspec** are not getting applied.

**To Reproduce**
To reproduce the issue create fission environment using below specs template file and then fetch the K8 resource created for the fission environment :
```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: test
  namespace: fission-function
spec:
  TerminationGracePeriod: 60
  builder: {}
  keeparchive: false
  poolsize: 3
  resources:
    limits:
        cpu: 1
        memory: 128Mi
    requests:
        cpu: 10m
        memory: 16Mi
  runtime:
    functionendpointport: 0
    image: <ENV_IMAGE>
    container:
       env:
       - name: ENABLE_TRACING
         value: "true"
       - name: ENABLE_LOGGING
         value: "true"
       volumeMounts:
       - mountPath: /etc/localtime
         name: tz-config
    loadendpointpath: ""
    loadendpointport: 0
    podspec:
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: tz-config
  version: 3

```

**Expected result** 
<pre>
kubectl get environment test  -n fission-function -o yaml

apiVersion: fission.io/v1
kind: Environment
metadata:
  annotations:
    fission-name: test
    fission-uid: 3146ef85-0e0a-4cd7-baf7-152f96409086
  creationTimestamp: "2020-09-15T15:54:27Z"
  generation: 1
  name: test
  namespace: fission-function
  resourceVersion: "8888"
  selfLink: /apis/fission.io/v1/namespaces/fission-function/environments/test
  uid: 33523f0f-fb08-4802-b0db-bc05f7d30a8a
spec:
  builder: {}
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources:
    limits:
      cpu: "1"
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 16Mi
  runtime:
    container:
      env:
      - name: ENABLE_TRACING
        value: "true"
      - name: ENABLE_LOGGING
        value: "true"
      name: ""
      resources: {}
      volumeMounts:
      - mountPath: /etc/localtime
        name: tz-config
    image: <ENV_IMAGE>
    podspec:
      containers: null
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: tz-config
  terminationGracePeriod: 60
  version: 3
</pre>

**Actual result**
<pre>
kubectl get environment test  -n fission-function -o yaml

apiVersion: fission.io/v1
kind: Environment
metadata:
  annotations:
    fission-name: test
    fission-uid: 3146ef85-0e0a-4cd7-baf7-152f96409086
  creationTimestamp: "2020-10-03T13:14:38Z"
  generation: 1
  name: test
  namespace: fission-function
  resourceVersion: "523333"
  selfLink: /apis/fission.io/v1/namespaces/fission-function/environments/test
  uid: e028c119-20bf-413d-b11c-11e0916587e7
spec:
  builder: {}
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    container: {}
    image: <ENV_IMAGE>
    podspec: {}
  terminationGracePeriod: 60
  version: 3
</pre>

As you can see above the configurations defined in **resources**, **runtime.container** and **runtime.podspec** are missing in K8 resource for fission environment. The same configuration works fine in 1.9.0
