### ISSUE TITLE
Constrain environment and builder pods, as well as core, with nodeSelector.

### ISSUE THREAD

**Issue by cerebrate** [fission/fission#1880]
**Is your feature request related to a problem? Please describe.**

I have a mixed-architecture cluster, linux/amd64 and linux/arm (with the possibility of adding windows/amd64 in the future). While I can get the core of Fission up and running easily enough using the following --

```
extraCoreComponentPodConfig:
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
```

-- in my values file when installing, when creating an environment, the resulting pods are not so constrained and can spawn on any node, and thus fail due to exec format errors.

**Describe the solution you'd like**

It would be great if the extraCoreComponentPodConfig setting could extend to also cover the non-core pods, or if an extra configuration setting could be added to allow nodeSelectors to be specified for these pods, which would make it possible to use Fission on mixed-architecture clusters.

**Describe alternatives you've considered**

Obviously my first thought was simply to build mixed-architecture images for all of Fission supporting both linux/amd64 and linux/arm, but unfortunately these images fail to build on arm in ways that are beyond my competence to fix.

**Comment by sanketsudake** [comment]
This has been inactive for 1653 days and is being marked stale. It will be closed in a future scrub if there's no further activity. Comment to keep it open.

**Comment by cerebrate** [comment]
It's been a long time and I personally don't run a mixed-architecture cluster any more, but since ARM64 processors are becoming more popular in all roles, it's still probably an issue worth addressing.

**Comment by sanketsudake** [comment]
This is supported today, on all three pod classes you named — closing as completed.

**Environment runtime pods** (poolmgr and newdeploy) via `spec.runtime.podspec`, and **builder pods**
via `spec.builder.podspec`:

```yaml
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: nodejs
  namespace: default
spec:
  version: 3
  runtime:
    image: fission/node-env
    podspec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
  builder:
    image: fission/node-builder
    podspec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
```

`NodeSelector` is on the pod-spec merge allowlist (`pkg/executor/util/merge_allowlist.go`) alongside
`Tolerations`, `Affinity` and `RuntimeClassName`, and the merge runs on every path that builds one of
these pods: poolmgr (`gp_deployment.go`), newdeploy (`newdeploy.go`) and buildermgr
(`environment_reconciler.go`). Core components stay on `extraCoreComponentPodConfig.nodeSelector`,
which you were already using.

For the mixed-architecture case specifically, `nodeSelector` is the blunt instrument; `affinity` is
also on the allowlist if you want `preferredDuringScheduling` rather than a hard constraint.

@cerebrate — you're right that this stayed worth addressing as arm64 spread. Reopen if the podspec
route falls short of what you had in mind.
