### ISSUE TITLE
Runtime container should follow same naming convention in pool manager and new deploy

### ISSUE THREAD

**Issue by sanketsudake** [fission/fission#2043]
**Fission/Kubernetes version**

Applicable to all Fission versions.

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Since the fission bug doesn't depend on the Kubernetes version

**Describe the bug**

Currently when the user mentions podspec for the environment, 

- Behaviour for pod spec with new deploy
If we are overriding the runtime container image, the container name needs to be the same as the function name.
```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: default
spec:
  builder: {}
  imagepullsecret: ""
  keeparchive: false
  poolsize: 1
  resources: {}
  runtime:
    image: fission/node-env
    podspec:
      containers:
      - name: hellojs
        image: fission/node-env
        env:
        - name: DEMO_GREETING
          value: "TESTING HELLO"
        - name: DEMO_FAREWELL
          value: "TESTING GOODBYE"
  version: 3
```
- Behaviour for pod spec with the pool manager 
If we are overriding the runtime container image, the container name needs to be the same as the environment name.
```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: default
spec:
  builder: {}
  imagepullsecret: ""
  keeparchive: false
  poolsize: 1
  resources: {}
  runtime:
    image: fission/node-env
    podspec:
      containers:
      - name: nodejs
        image: fission/node-env
        env:
        - name: DEMO_GREETING
          value: "TESTING HELLO"
        - name: DEMO_FAREWELL
          value: "TESTING GOODBYE"
  version: 3
```
In the above cases,  if we specify different container names, the environment pod ends up having conflicting containers and the pod fails to specialize.

**To Reproduce**
As mentioned above try different podspec combination.

**Expected result**

We should follow the same convention in pool manager and new deploy, ie, use the same naming convention for runtime container.

**Actual result**
Failure in environment pod creation with, container spec merge failing.

**Screenshots/Dump file**

**Additional context**

**Comment by sanketsudake** [comment]
Raised PR https://github.com/fission/fission/pull/2044

**Comment by sanketsudake** [comment]
Merged PR, so closing issue. It should be available in 1.13 release. Thanks, @kbbqiu for identifying the issue. 🎉

**Comment by sanketsudake** [comment]
With this fix we had to change container name for default container which runs function.
So if you have any automation to fetch function logs using function container name you may need to it.

We would recommend using pod label to function logs.

```
kubectl logs -f -l functionName=hello -n <fn-namespace> -c <env-name>
```

Typically newdeploy function pod would have environment and function labels attached to it.
You can use any function lables to identify pod by function name.

```
  labels:
    environmentName: nodejs
    environmentNamespace: default
    environmentUid: 6e445095-4f08-431d-a423-629296fecb0a
    executorType: newdeploy
    functionName: hello
    functionNamespace: default
    functionUid: babbb708-a619-4b4c-81e3-a7e90cc96696
    pod-template-hash: 665bd8b8c7
```
