### ISSUE TITLE
Fission Chart: Redhat Chart Verifier Checks 

### ISSUE THREAD

**Issue by sanketsudake** [fission/fission#2280]
**Describe the bug**

We need to fix the Fission chart so that we are ready for Redhat Certification.

**To Reproduce**

How to run checks ?
1. Clone Fission repository
2. 
    ```
    cd fission/charts
    docker run -v $(pwd):/charts --rm quay.io/redhat-certification/chart-verifier verify /charts/fission-all
    ```

**Expected result**
All checks should pass.

**Actual result**
Failing checks:
1. [ ] v1.1/has-kubeversion 
2. [ ] v1.0/images-are-certified
3. [ ] v1.0/chart-testing
4. [ ] v1.0/required-annotations-present
5. [ ] v1.0/contains-values-schema
6. [ ] v1.0/contains-test

**Screenshots/Dump file**

```yaml
results:
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: FAIL
      reason: Values schema file does not exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: |-
        Image is not Red Hat certified : index.docker.io/fission/fission-bundle:v1.15.0 : No images found for Registry/Repository: index.docker.io/fission/fission-bundle
        Image is not Red Hat certified : fission/reporter:v1.15.0 : Respository not found: fission/reporter
        Image is not Red Hat certified : fission/pre-upgrade-checks:v1.15.0 : Respository not found: fission/pre-upgrade-checks
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: FAIL
      reason: |-
        Error running process: executing helm with args "install fission-all-9oat75s925 /root/.cache/chart-verifier/_charts_fission_all/fission-all --namespace default --wait --values /tmp/chart-testing-2870804243/values.yaml": exit status 1
        ---
        Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: FAIL
      reason: 'Missing required annotations: [charts.openshift.io/name]'
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/contains-test
      type: Mandatory
      outcome: FAIL
      reason: Chart test files do not exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: FAIL
      reason: Kubernetes version is not specified
```

**Additional context**

Refer [redhat-certification/chart-verifier](https://github.com/redhat-certification/chart-verifier/) for more info
