### ISSUE TITLE
Host based routing help

### ISSUE THREAD

**Issue by BenHesketh21** [fission/fission#2296]
**Is your feature request related to a problem? Please describe.**
I would like to set up host based routing, here is my set up, I want functions deployed to different namespaces and these are the same functions but at different points in the pipeline, and then when I create a trigger I want env1.[our-domain].com/functions/[function-name] to go to the function in namespace env1 and env2.[our-domain].com/functions/[function-name] to go to a function with the same name but in namespace env2.

But when I set up the ingresses all of them, regardless of host or path, point to the router which will have 2 functions with the same url /functions/[function-name] and not care about the difference.

I see when you create a route on the CLI that you can specify the function namespace but it doesn't seem to actually make a difference.

**Describe the solution you'd like**
It would be great if you could specify a namespace the function is in and the router be able to differentiate despite them having the same name.

**Describe alternatives you've considered**
I could do url based routing by having [our-domain].com/functions/env1/[function-name] but we always do host based routing so it would be better if we had that option so we can remain consistent.

**Comment by jrhunger** [comment]
As a workaround, it seems you can apply the below, which is just the fission-all/templates/router/role-kubernetes.yaml from the helm chart, with the namespace on each object changed from default to fission.  The ingresses get created in fission namespace but they do work.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "fission-router"
  namespace: fission
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
# Source: fission-all/templates/router/role-kubernetes.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "fission-router"
  namespace: fission
subjects:
  - kind: ServiceAccount
    name: "fission-router"
    namespace: fission
roleRef:
  kind: Role
  name: "fission-router"
  apiGroup: rbac.authorization.k8s.io
```
