### ISSUE TITLE
internal error when using secrets in different namespaces

### ISSUE THREAD

**Issue by shaunc** [fission/fission#2304]
**Fission/Kubernetes version**

<pre>
$ fission --version
fission version
client:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1
server:
  fission/core:
    BuildDate: "2021-11-23T09:29:28Z"
    GitCommit: 5349a591
    Version: v1.15.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)** EKS

**Describe the bug**

When I include a spec with secrets in another namespace, the spec validates, but the function doesn't run and collecting the logs gives an internal error.

**To Reproduce**
I am trying to use a secret in a different namespace when deploying a function and package from a spec. 
The spec for the function is currently:
```yaml
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: cdf-send-sftp-check
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: cdf-send-sftp
      namespace: default
    functionName: main.check
  requestsPerPod: 1
  resources: {}
  secrets:
  - name: legacy-database-config
    namespace: crane-web
  - name: sftp-send
    namespace: crane-web
```
When I try to invoke the function, I get  `error sending request to function`, and in the logs I see `Error querying logs: Internal error - 502 Bad Gateway`. I notice in the fission router logs:
```json
{"level":"error","ts":"2022-01-21T05:20:40.603Z","logger":"triggerset.http_trigger_set.98856c70-db8f-4b45-a736-214d38b19fce","caller":"httputil/reverseproxy.go:295","msg":"error sending request to function","trace_id":"6fe972706683b59af47f7e7322c4818a","error":" - Internal error - [cdf-send-sftp-check] error creating service for function: Internal error - error fetching secrets/configs: error getting secret from kubeapi","function":{"namespace":"default","name":"cdf-send-sftp-check"},"status":"Internal Server Error","code":500,"stacktrace":"net/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/http/httputil/reverseproxy.go:295\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\tpkg/router/functionHandler.go:529\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/http/server.go:2049\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/sanket/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\tpkg/router/mutablemux.go:52\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/http/server.go:2867\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/http/server.go:1932"}
```

**Expected result**

If it is impossible to use a different namespace for secrets, this should be flagged during validation.
**Actual result**
Passes validation.

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>
[fission-dump_1642741633.zip](https://github.com/fission/fission/files/7910672/fission-dump_1642741633.zip)

**Additional context**

I tried to put the function and package in the namespace with the secrets, but then the function doesn't show up when I do `fission fn list`. Can one put functions in other namespaces nevertheless? I want to support multiple clients with one fission installation in one cluster, so want to have secrets in different places -- if the functions/packages also can to be in different places, that is good.

**UPDATE**: error goes away when the function, package and trigger are all in the same namespace. I can't see the function with `fission fn list` but I can invoke it via curl with an httptrigger. So validation should check that the function and secrets are in the same namespace; documentation should note that you can put entities in other namespaces but that they won't be accessible by the cli.

**UPDATE 2**: ah right -- so the above isn't a good workaround as then I can't look at logs or otherwise interact with the function except through the http trigger.
