### ISSUE TITLE
StorageSvc persists nothing, builder environments has only emptyDir mounted

### ISSUE THREAD

**Issue by torbendury** [fission/fission#2307]
**Fission/Kubernetes version**

```bash
  $ helm list
NAME                     	NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART                  	APP VERSION
fission                  	fission       	5       	2022-01-17 20:44:51.185779675 +0100 CET	deployed	fission-all-v1.15.1    	v1.15.1 

  $ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-1555+9e8f924492b7d7-dirty", GitCommit:"9e8f924492b7d70b0216d20529f3471eed59463c", GitTreeState:"dirty", BuildDate:"2021-11-10T16:00:46Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Kubernetes platform (e.g. Google Kubernetes Engine)**

OKD

**Describe the bug**

As the [documentation](https://fission.io/docs/architecture/storagesvc/) guides, the StorageSvc should persist any functions with size >256KB. In my case, the `PersistentVolumeClaim` is empty (except a `lost+found` directory) and my build environment (Python3.8) isn't able to persist anything throughout a restart because of the `emptyDir: {}` mounts.

**To Reproduce**

- Install above fission version with standard values
- upload functions with arbitrary size
- wonder where it gets persisted

**Expected result**

- StorageSvc persists any function (maybe even ones with <256KB? Where do these get stored at the moment?)

**Actual result**

- StorageSvc `PersistentVolumeClaim` is completely empty

**Additional context**

I can't tell what the "package size over 256KB" means - are 256KB including resolved dependencies, e.g. Python Flask? Also, I didn't manage to find out where user functions with size <256KB are being persisted right now.

**Comment by blackfly19** [comment]
Hi @torbendury . I tested it out with the specified versions but I am not able to reproduce it. The following pvc is being created for me.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: fission
    meta.helm.sh/release-namespace: fission
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: fission1.15-bug-test-control-plane
  creationTimestamp: "2022-05-27T07:21:20Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: fission-storage
    app.kubernetes.io/managed-by: Helm
    chart: fission-all-v1.15.1
    release: fission
  name: fission-storage-pvc
  namespace: fission
  resourceVersion: "1102"
  uid: ad401439-6f84-488f-b10c-0648c1216031
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-ad401439-6f84-488f-b10c-0648c1216031
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
```
Its attached to the storagesvc.
```
spec:
  containers:
  - args:
    - --storageServicePort
    - "8000"
    - --storageType
    - local
    command:
    - /fission-bundle
    env:
    - name: PRUNE_INTERVAL
      value: "60"
    - name: DEBUG_ENV
      value: "false"
    - name: PPROF_ENABLED
      value: "false"
    - name: OPENTRACING_ENABLED
      value: "false"
    - name: TRACE_JAEGER_COLLECTOR_ENDPOINT
    - name: TRACING_SAMPLING_RATE
      value: "0.5"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.1"
    - name: OTEL_PROPAGATORS
      value: tracecontext,baggage
    image: index.docker.io/fission/fission-bundle:v1.15.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      initialDelaySeconds: 35
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: storagesvc
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 30
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /fission
      name: fission-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8pkdk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: fission1.15-bug-test-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fission-svc
  serviceAccountName: fission-svc
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: fission-storage
    persistentVolumeClaim:
      claimName: fission-storage-pvc
  - name: kube-api-access-8pkdk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```
I also restarted the storagesvc and I was able to find the archives created earlier.
So can you specify exact steps to reproduce this issue.

As for files less than 256kb we store it directly in the package custom resource.
```
spec:
  deployment:
    checksum: {}
    literal: UEsDBBQACAAIAAU7MlQAAAAAAAAAAAAAAAAJAAkAUkVBRE1FLm1kVVQFAAEaa+ZhrFOxbtswFNz1FVd7KBBYalB0KoIsRYF6bjp0igjpyXotRQrkk23164tHJrKduEOBeDAg8nR37+7poecIjjAOdDTDaAm+QxPICLsdDFoarZ8HcoLRNL/NjnBg6TFMVni0VHRsKYJdY6dWX4l+IEQxwg1aIwbsIHQUKLAqivV6jS/KT0nU7Tl4p/xFUdd10XGM7NNFtkEoS2cGwjhL7x3Kkgd18QT8kI9LcvvPt9Wn6jY0KMs9hcTyMXFeaOIPj8lLnsNYi9lPIR3F7EER5a+QZ0y29eSmGmfcVHKUK6Td5Bph74riO7uGID0Fggm0BJUFNiqG3uwJ4hFHaribNYhHchLm0bOTR4gvOh+UZCGugK1EdD4MRrSx+i4NodHcV3fPsPxcV9g6+CkUT6VuIL2R9xH1YNhV+ldv1EGY3CKRL2stLMPGua4uW1mgl9UsQaHUIk5VNb6lFzEq4nlSLG5OkT5QFLD8Q1f09qVqfvmnnxB7P9kWkVIDWH0ja/0GBx9su8JAMZqdLmGxXuPH2OYlP485e/jasmipyp3Iqek9VltEwy16JdXfuxXuF9KLvUjc2cPrD+h/l+yM7GTzajpTRl5p5XURb5u484eUevqUHB02oJaF2rPM/wYAAP//UEsHCDo9pRrdAQAAawQAAFBLAwQUAAgACAAFOzJUAAAAAAAAAAAAAAAACwAJAF9faW5pdF9fLnB5VVQFAAEaa+ZhAQAA//9QSwcIAAAAAAUAAAAAAAAAUEsDBBQACAAIAAU7MlQAAAAAAAAAAAAAAAAHAAkAbWFpbi5weVVUBQABGmvmYVSNUaoDIQxF/11F8Evh4QIevN9HdyFS4zStGkkcaHdfBmbK9O8m3HtOEW5QatIHUBssE66rCPYZ0xhmf+lLjyiYcqGKx81qTMYCLVF3/tcAwJkQKi8LSqBe2NkLWW++KpkE/oA1jDRvIZP01NDFuCli3MuCc5X+UYct/FNFd+zuTN2dkD9gG6qmBcN8Tuu9eQcAAP//UEsHCKx3J8iVAAAA5wAAAFBLAwQUAAgACAAFOzJUAAAAAAAAAAAAAAAACwAJAG1lc3NhZ2UudHh0VVQFAAEaa+Zh8kjNycnXUSjPL8pJUeQCBAAA//9QSwcIGKdVexQAAAAOAAAAUEsDBBQACAAIAAU7MlQAAAAAAAAAAAAAAAALAAkAcmVhZGZpbGUucHlVVAUAARpr5mFKSU1TKEpNTHHLzEnVyEvMTdW04lJQUFAozyzJUMgvSM2DCCokFiukQWRAoCi1pLQoTyFND6RVQ5MLEAAA//9QSwcI6dkurD8AAABGAAAAUEsBAhQDFAAIAAgABTsyVDo9pRrdAQAAawQAAAkACQAAAAAAAAAAALSBAAAAAFJFQURNRS5tZFVUBQABGmvmYVBLAQIUAxQACAAIAAU7MlQAAAAABQAAAAAAAAALAAkAAAAAAAAAAAC0gR0CAABfX2luaXRfXy5weVVUBQABGmvmYVBLAQIUAxQACAAIAAU7MlSsdyfIlQAAAOcAAAAHAAkAAAAAAAAAAAC0gWQCAABtYWluLnB5VVQFAAEaa+ZhUEsBAhQDFAAIAAgABTsyVBinVXsUAAAADgAAAAsACQAAAAAAAAAAALSBNwMAAG1lc3NhZ2UudHh0VVQFAAEaa+ZhUEsBAhQDFAAIAAgABTsyVOnZLqw/AAAARgAAAAsACQAAAAAAAAAAALSBjQMAAHJlYWRmaWxlLnB5VVQFAAEaa+ZhUEsFBgAAAAAFAAUARAEAAA4EAAAAAA==
    type: literal
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-03-11T07:42:06Z"
```

The above literal section contains the function encoded in base64.
