### ISSUE TITLE
Creating one pod per request on newDeploy to allow better volume support

### ISSUE THREAD

**Issue by Docteur-RS** [fission/fission#2384]
**Is your feature request related to a problem? Please describe.**
Our goal is to make a datapipeline. This means downloading large files, do work on them then start a new function and repeat.

Our requirements are:
* One pod per request
* Volumes customisations
* Scale to 0

Fission already provides one pod per request when using poolMngr. But poolMngr does not allow scale to 0, the whole point being to always have one pod ready to serve requests. So this is no go...

Now newDeploy does scale to 0. But unfortunatly it doesn't allow one pod per request.

---

Why do we need this ?
=> We want fresh volumes for each of our pods. This is achieved using ephemeral storage creating new PVCs on the fly. When using poolMngr the PVC is always UP so this ends up costing money for nothing. Using newDeploy all requests go to the same pod and then the volume is not a fresh one...
This doesn't break the "stateless" principle as the volume is ephemeral. It only acts as an exention of the file system. Some files are too large to be downloaded on the Kubernetes node. In the current state of the project we can use a PVC but all functions will share it.   
The current implementation breaks the FAAS principles.  

**Describe the solution you'd like**
We need a mix of poolMngr and newDeploy. The scale to 0 of newDeploy and the one pod per request (--yolo) of poolMngr.

**Additional context**
This is how we define our ephemeral storage 
```
        - name: my-light-volume
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: my-volume
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "csi-cinder-high-speed"
                resources:
                  requests:
                    storage: 1Gi
```
It works well with the current volume management provided with Fission. We just need a new pod for each request...
