### ISSUE TITLE
POST request became GET

### ISSUE THREAD

**Issue by sjk7524068** [fission/fission#2494]
### Describe the bug
I have made a POST method myadd, but somehow when I do reuqest, logs from router shows that it's a GET request.

I know I may config something wrong, Is there a way to fix this?

###  fission version:
```bash
client:
  fission/core:
    Version: 1.12.0
server:
  fission/core:
    Version: 1.12.0
```

### kubectl version
```bash
Client Version: version.Info {
	Major: "1",
	Minor: "21",
	GitVersion: "v1.21.1",
	GitCommit: "5e58841cce77d4bc13713ad2b91fa0d961e69192",
	GitTreeState: "clean",
	BuildDate: "2021-05-12T14:18:45Z",
	GoVersion: "go1.16.4",
	Compiler: "gc",
	Platform: "linux/amd64"
}
Server Version: version.Info {
	Major: "1",
	Minor: "18+",
	GitVersion: "v1.18.20-eks-154371",
	GitCommit: "1543713dd4762c0a4f87b7af825b0e5c2ece7873",
	GitTreeState: "clean",
	BuildDate: "2022-02-16T20:59:03Z",
	GoVersion: "go1.13.15",
	Compiler: "gc",
	Platform: "linux/amd64"
}
```

###  logs from my router
```bash
2022-07-26T01:58:05.130Z        INFO    router/router.go:96     path   
 {
"path": "/dev/myadd", 
"method": "GET", 
"header": {"Accept":["*/*"],
"Accept-Encoding":["gzip, deflate, br"],
"Postman-Token":["a8aa9639-3bce-4076-8370-074401c9390c"],
"Referer":["http://domain_addr/dev/myadd"],
"User-Agent":["PostmanRuntime/7.29.0"],
"X-Amzn-Trace-Id":["Root=1-62df4a2d-488c771c72e5d8cd16db4a7c"],
"X-Forwarded-For":["ip_addr"],
"X-Forwarded-Host":[host_addr],
"X-Forwarded-Port":["80"],
"X-Forwarded-Proto":["http"],
"X-Original-Forwarded-For":[ip_addr],
"X-Original-Uri":["/dev/myadd"],
"X-Real-Ip":[ip_addr],
"X-Request-Id":["7f30c536c3e182d318bf5415496a3863"],
"X-Scheme":["http"]
}
```

### my fission spec route yaml config

```yaml
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: myadd
  namespace: fission-csp-dev
spec:
  createingress: false
  functionref:
    functionweights: null
    name: myadd
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /dev/myadd
    tls: ""
  method: POST
  relativeurl: /dev/myadd
```
