### ISSUE TITLE
Environment and functions disappering after node restart

### ISSUE THREAD

**Issue by venugopalnaidu** [fission/fission#265]
Hello,

I observed environment deletion with kubernetes single node cluster restart.

I created an environment, function and a route and all are working fine. Once i reboot the server i am not able to fetch earlier created environment and fission functions. While installing fission i created a persistent volume mount for /filestore to keep all the functions persistent. The below are the poolmgr logs what i got after reboot 

**2017/07/24 11:08:31 starting poolmgr at port 8888
2017/07/24 11:08:31 Cleaning up deployment python-8e494c49-7bf3-467a-bcd9-c1885b7b74f5-o0sxvc9g
2017/07/24 11:08:31 Cleaning up replicaset python-8e494c49-7bf3-467a-bcd9-c1885b7b74f5-o0sxvc9g-385640210
2017/07/24 11:14:31 Cleaning up pod python-8e494c49-7bf3-467a-bcd9-c1885b7b74f5-o0sxvc9g-38564116kr
2017/07/24 11:14:31 Cleaning up pod python-8e494c49-7bf3-467a-bcd9-c1885b7b74f5-o0sxvc9g-385646rd02
2017/07/24 11:14:31 Cleaning up pod python-8e494c49-7bf3-467a-bcd9-c1885b7b74f5-o0sxvc9g-3856483brb
2017/07/24 11:14:31 Cleaning up pod python-8e494c49-7bf3-467a-bcd9-c1885b7b74f5-o0sxvc9g-38564rnhqm**

**Comment by soamvasani** [comment]
In the current release, you also have to create a persistent volume mount for the etcd deployment, and mount it at `/default.etcd`.

Here's an example:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd
  namespace: fission
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd
        env:
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://etcd:2379
        volumeMounts:
          - mountPath: "/default.etcd"
            name: vol-etcd
      volumes:
      - name: vol-etcd
        persistentVolumeClaim:
          claimName: etcdclaim
```

and 

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcdclaim
  namespace: fission
  annotations:
    volume.beta.kubernetes.io/storage-class: "ssd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```
