### ISSUE TITLE
Can not reapply specs containing HttpTrigger - false positive duplicate detection

### ISSUE THREAD

**Issue by laurence-hudson-mindfoundry** [fission/fission#2658]
**Fission/Kubernetes version**

* Fission CLI = v1.17.0
* Fission Server = v1.17.0
* K8s  = EKS v.1.23 (v1.23.10)
* kubectl = v1.23.10
* Ingress = ingress-nginx v4.3.0

**Kubernetes platform (e.g. Google Kubernetes Engine)**

AWS EKS

**Describe the bug**

Running `fission spec apply` twice without changes to HttpTriggers produces `Error: error applying specs: HTTPTrigger apply failed: Resource exists - HTTPTrigger with same Host, URL & method already exists`

**To Reproduce**

* [https://editor.mergely.com/R4RXQb32/](https://editor.mergely.com/R4RXQb32/)
* Left/before is the files & log from the first `fission spec apply` which seemingly works correctly
* Right/after is the files & log from the second `fission spec apply` (after changing the function archive content) which errors

As should be obvious from the diff, the function haven't changed, nor has the spec config uid

I've also tried all combinations of `--allowconflicts=true`, `--validation=false` & `--delete`, but they all produce the same behavoir.

**Expected result**

`checkHTTPTriggerDuplicates` should not identify these triggers as duplicates, rather they are already in the desired state and should not be modified.

**Actual result**

> Error: error applying specs: HTTPTrigger apply failed: Resource exists - HTTPTrigger with same Host, URL & method already exists

**Screenshots/Dump file**

* [https://editor.mergely.com/R4RXQb32/](https://editor.mergely.com/R4RXQb32/)
* Left/before is the files & log from the first `fission spec apply` which seemingly works correctly
* Right/after is the files & log from the second `fission spec apply` (after changing the function archive content) which errors

[fission-dump_1670327094.zip](https://github.com/fission/fission/files/10165914/fission-dump_1670327094.zip)

**Comment by NikhilSharmaWe** [comment]
Hey, @laurence-hudson-mindfoundry I tried to reproduce the issue but when I reapply a spec by just changing the name of the `package ref` in both functions and not making any changes in the `HTTP trigger`, the expected error is not logged. Instead, new packages are created and functions are updated since I change the name of the `package ref`.

So, I am not getting that error that is specified in the issue.

My fission cli and server version are also the same: `v1.17.0`

**Comment by soharab-ic** [comment]
Please try latest Fission version `v1.20.5` and re-open if issue remains.

**Comment by ProjectMoon** [comment]
I have this exact issue, running on Minikube.

Here's a spec file that causes it:

```yaml
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: tasks-create
spec:
  createingress: false
  functionref:
    functionweights: null
    name: create-task
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /tasks/create
    tls: ""
  method: ""
  methods:
  - POST
  - OPTIONS
  prefix: ""
  relativeurl: /tasks/create
```
