### ISSUE TITLE
Environment spec config -- preStop not working as expected

### ISSUE THREAD

**Issue by sjk7524068** [fission/fission#2686]
**Fission/Kubernetes version**

<pre>
$ fission version v1.17.0
$ kubectl version v1.25.1
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
**
**Describe the bug**

Spec config preStop is not working as expected, I want a fresh new preStop config be worked, but new preStop command was actually merge  into an old exec command list.
**To Reproduce**

```yaml
# Environment spec config
spec:
  runtime:
    container:
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sleep", "0"] # here
```

**Expected result**

Get deploy pod config information by k8s
```yaml
spec:
  containers:
    image: xxxx
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "0"
    name: xxx
```

**Actual result**
```yaml
spec:
  containers:
    image: xxxx
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "5"
          - /bin/sleep
          - "0"
    name: xxx
```
**Screenshots/Dump file**

**Additional context**
