### ISSUE TITLE
create mqt with Kafka SASL failed

### ISSUE THREAD

**Issue by BTYHunter** [fission/fission#2823]
I have built Kafka and kafka with SASL two brokers in my cluster, and install KEDA latest version 2.11.1.
Following this `https://github.com/fission/examples/blob/master/samples/kafka-keda-sasl/README.md` faild. In this tutorial `Note: Please ensure that you are using Kafka Keda Connector version 0.9 or higher`，how can I find the `Kafka Keda Connector version`, is that KEDA version?

Following this `https://github.com/fission/examples/blob/master/samples/kafka-keda/README.md` successed.

**Fission version**
v1.17.0 

**Kubernetes version**
v1.21.5-eki.0

**Describe the bug**

Following this `https://github.com/fission/examples/blob/master/samples/kafka-keda-sasl/README.md`  tutorial，I got error as below.

pod/mqtrigger-keda log:
```bash
{
"level":"error","ts":"2023-07-12T12:10:42.863Z",
"caller":"mqtrigger/scalermanager.go:101",
"msg":"Failed to create ScaledObject",
"error":"admission webhook \"vscaledobject.kb.io\" denied the request: failed to get API group resources: unable to retrieve the complete list of server APIs: autoscaling/v2: the server could not find the requested resource",
"stacktrace":"github.com/fission/fission/pkg/mqtrigger.mqTriggerEventHandlers.func1.1\n\tpkg/mqtrigger/scalermanager.go:101"
}
```
pod/mqtrigger-kafka log:
```bash
{
"level":"info","ts":"2023-07-12T12:09:38.815Z",
"logger":"message_queue_trigger_manager","caller":"mqtrigger/mqtmanager.go:196",
"msg":"Unsubscribe failed","trigger_name":"kafkatest"}
{
"level":"warn",
"ts":"2023-07-12T12:10:44.766Z",
"logger":"message_queue_trigger_manager",
"caller":"mqtrigger/mqtmanager.go:165",
"msg":"failed to subscribe to message queue trigger",
"error":"kafka: client has run out of available brokers to talk to: EOF",
"trigger_name":"kafkatest"
}
```

kafka-config-sasl.yaml is:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: default
stringData:
  sasl: "plaintext"
  username: "test"
  password: "token:ABC"
  tls: "enable"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keda-kafka-configmap
  namespace: default
data:
  brokers: "x.x.x.x:x"
  request-topic: "test-input"
  response-topic: "test-output"
  error-topic: "test-error"
```
create mqt command is:
```bash
fission mqt create --name kafkatest --function kafka-consumer --mqtype kafka --mqtkind keda \
    --topic test-input --resptopic test-output --errortopic test-error --maxretries 3 \
    --metadata bootstrapServers=x.x.x.x:x \
    --metadata topic=test-input  --cooldownperiod=30 \
    --pollinginterval=5 --secret keda-kafka-secrets
```

k get MessageQueueTrigger kafkatest -o yaml
```yaml
apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: "2023-07-13T05:52:59Z"
  generation: 1
  name: kafkatest
  namespace: default
  resourceVersion: "12974828"
  uid: 9916b0a8-0161-43be-ab3f-4e550c5066b0
spec:
  contentType: application/json
  cooldownPeriod: 30
  errorTopic: test-error
  functionref:
    functionweights: null
    name: kafka-consumer
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: kafka
  metadata:
    bootstrapServers: x.x.x.x:x
    topic: test-input
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 5
  respTopic: test-output
  secret: keda-kafka-secrets
  topic: test-input
```

**Expected result**

Fission that supports kafka sasl should works.

**Actual result**
mqtrigger-kafka says 'client has run out of available brokers to talk to'.

Thank you for you reply.
