### ISSUE TITLE
Fission watch all namespaces

### ISSUE THREAD

**Issue by gkaskonas** [fission/fission#2913]
**Is your feature request related to a problem? Please describe.**
I want to configure fission to monitor all namespaces (use wildcards).
**Describe the solution you'd like**
Instead of using Roles, use ClusterRoles and add an ability to monitor all namespaces
**Describe alternatives you've considered**

**Additional context**
We create a lot of namespaces dynamically and would like an ability to deploy fission related resources into those namespaces. 
Specifying a static list into helm is not an option

**Comment by dsegurakaliop** [comment]
Please, please, please take this issue in consideration.

We can help to test the feature on a dedicated Kubernetes cluster now.

Please contact me if we can help to add this feature ASAP.

**Comment by Stradivario** [comment]
Any progres on this ?

Since right now i am struggling a lot because of these new RBACS

I want to create also a dynamically namespaces without specifiyng them in helm values.yaml since this recreates the whole cluster and every pod and environment created for every namespace added. 
It is just insane. 

I made some scripts to manually patch the rbac roles and adding also directly to the deployments of fission literally injecting values and still fission recreates everything due to the executor trying to adopt existing resources. Even if this is set to false still it recreates every pod leading to major downtime of the cluster for all tenants and namespaces.

I am forced to create fission per namespace but then this means multiple load balancers and multiple storage buckets etc... which is not an option.

I tried every possible variant but still everything is recreated. 


I am thinking of downgrading to v1.17 where everything was running smoothly and as expected.




These are my attempts to fix this behavior manuall

```yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-buildermgr-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - environments
  - functions
  - packages
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-buildermgr
  namespace: new-namespace
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-executor-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - environments
  - functions
  - packages
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-executor
  namespace: new-namespace
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - replicationcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - replicasets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-fluentbit
  namespace: new-namespace
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-kubewatcher-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - environments
  - functions
  - kuberneteswatchtriggers
  - packages
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-kubewatcher
  namespace: new-namespace
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - pods
  - secrets
  - services
  - replicationcontrollers
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-fission-fetcher
  namespace: new-namespace
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
- apiGroups:
  - fission.io
  resources:
  - packages
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-fission-builder
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - packages
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: new-namespace
  name: fission-fission-fetcher-websocket
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-kafka-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - environments
  - functions
  - messagequeuetriggers
  - packages
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-kafka
  namespace: new-namespace
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - pods
  - secrets
  - services
  - replicationcontrollers
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - replicasets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-keda-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - environments
  - functions
  - messagequeuetriggers
  - packages
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-keda
  namespace: new-namespace
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - replicationcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - replicasets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keda.sh
  resources:
  - scaledjobs
  - scaledobjects
  - scaledjobs/finalizers
  - scaledjobs/status
  - triggerauthentications
  - triggerauthentications/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - keda.k8s.io
  resources:
  - scaledjobs
  - scaledobjects
  - scaledjobs/finalizers
  - scaledjobs/status
  - triggerauthentications
  - triggerauthentications/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-router-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - environments
  - functions
  - httptriggers
  - packages
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-router
  namespace: new-namespace
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-storagesvc-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - packages
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-timer-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - environments
  - functions
  - packages
  - timetriggers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fission-timer
  namespace: new-namespace
rules: []
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-buildermgr-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-buildermgr
  namespace: fission
roleRef:
  kind: Role
  name: fission-buildermgr-fission-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-buildermgr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-buildermgr
  namespace: fission
roleRef:
  kind: Role
  name: fission-buildermgr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-executor-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-executor
  namespace: fission
roleRef:
  kind: Role
  name: fission-executor-fission-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-executor
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-executor
  namespace: fission
roleRef:
  kind: Role
  name: fission-executor
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-fluentbit
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-fluentbit
  namespace: fission
roleRef:
  kind: Role
  name: fission-fluentbit
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-kubewatcher-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-kubewatcher
  namespace: fission
roleRef:
  kind: Role
  name: fission-kubewatcher-fission-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-kubewatcher
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-kubewatcher
  namespace: fission
roleRef:
  kind: Role
  name: fission-kubewatcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fission-fission-fetcher
  namespace: new-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fission-fission-fetcher
subjects:
- kind: ServiceAccount
  name: fission-fetcher
  namespace: new-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fission-fission-builder
  namespace: new-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fission-fission-builder
subjects:
- kind: ServiceAccount
  name: fission-builder
  namespace: new-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fission-fission-fetcher-websocket
  namespace: new-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fission-fission-fetcher-websocket
subjects:
- kind: ServiceAccount
  name: fission-fetcher
  namespace: new-namespace
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-kafka-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-kafka
  namespace: fission
roleRef:
  kind: Role
  name: fission-kafka-fission-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-kafka
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-kafka
  namespace: fission
roleRef:
  kind: Role
  name: fission-kafka
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-keda-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-keda
  namespace: fission
roleRef:
  kind: Role
  name: fission-keda-fission-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-keda
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-keda
  namespace: fission
roleRef:
  kind: Role
  name: fission-keda
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-router-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-router
  namespace: fission
roleRef:
  kind: Role
  name: fission-router-fission-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-router
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-router
  namespace: fission
roleRef:
  kind: Role
  name: fission-router
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-storagesvc-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-storagesvc
  namespace: fission
roleRef:
  kind: Role
  name: fission-storagesvc-fission-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-timer-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-timer
  namespace: fission
roleRef:
  kind: Role
  name: fission-timer-fission-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fission-timer
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-timer
  namespace: fission
roleRef:
  kind: Role
  name: fission-timer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: '-2'
  name: fission-preupgrade-fission-cr
  namespace: new-namespace
rules:
- apiGroups:
  - fission.io
  resources:
  - canaryconfigs
  - environments
  - functions
  - httptriggers
  - kuberneteswatchtriggers
  - messagequeuetriggers
  - packages
  - timetriggers
  verbs:
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  name: fission-preupgrade-fission-cr
  namespace: new-namespace
subjects:
- kind: ServiceAccount
  name: fission-preupgrade
  namespace: fission
roleRef:
  kind: Role
  name: fission-preupgrade-fission-cr
  apiGroup: rbac.authorization.k8s.io

```


```bash
kubect apply -f ./rbac-new-namespace.yaml
```




After that manually adding the namespace to every fission component

```bash

# The new namespace to add
NEW_NS="new-namespace"

# Loop through all core components to update their watched namespace list
for deploy in executor router buildermgr kubewatcher mqtrigger-keda storagesvc timer; do
  # Get existing value
  CURRENT_VAL=$(kubectl -n fission get deploy $deploy -o jsonpath='{.spec.template.spec.containers[0].env[?(@.name=="FISSION_RESOURCE_NAMESPACES")].value}')
  
  # Append new namespace if not already present
  if [[ $CURRENT_VAL != *"$NEW_NS"* ]]; then
    UPDATED_VAL="${CURRENT_VAL},${NEW_NS}"
    echo "Updating $deploy to watch: $UPDATED_VAL"
    kubectl -n fission set env deployment/$deploy FISSION_RESOURCE_NAMESPACES="$UPDATED_VAL"
  else
    echo "$deploy is already watching $NEW_NS"
  fi
done
```

Still the cluster recreates and every pod and namespace. 
This is very confusing and it is leading to scaling the cluster nodes until the deployment is finished and everything inside the cluster running with fission is with downtime at least 5 minutes.
I have specified also multiple replicas per fission deployments and maxRollout strategies and things like that but no nothing works and still recreates.

It appears that executor is the single point of failure since you cannot replicate it you can just provision another executor on deployment but until the provisioning is done the current executor is non responsive until the new replica is successfully deployed.

My god it has being a hustle!


Here is my two cents on the topic explained also here as a ticket https://github.com/fission/fission/issues/3298

I would love to have ability for fission to watch all namespaces 
For example in many other charts if you specify empty array [] it fallbacks to watch all namespaces
I would love fission to have such a functionality. Just pass empty array and forget about namespaces.

Any other solutions guys to this problem ?


@sanketsudake 

Please help us my man! 
We are struggling!
