### ISSUE TITLE
For newdeploy functions, idletimeout kicks in when the function pod starts, and not when it is done serving the request

### ISSUE THREAD

**Issue by sharang-lyric** [fission/fission#2992]
**Fission/Kubernetes version**

<pre>
$ fission version v1.20.3
$ kubectl version v1.27.2
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Docker Desktop

**Describe the bug**

I have a newdeploy function that takes 20 seconds to respond. I have configured idletimeout to be 10 seconds. When the function is called, the idletimeout timer kicks in as soon as the pod is up, and the pod is forcefully terminated even though it is still in the middle of serving the request. My expectation is that the idletimout timer should kick in after the response has been request is served and the response is sent.
The idletimeout works perfectly fine in case of poolmgr.

**To Reproduce**

1. Create environment with following manifest
```yaml
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: hellopy
  namespace: default
spec:
  poolsize: 0
  runtime:
    image: fission/python-env
    podspec:
      containers:
      - image: fission/python-env
        imagePullPolicy: Always
        name: hellopy
  version: 3
```
2. Create package with the following manifest
```yaml
apiVersion: fission.io/v1
kind: Package
metadata:
  name: hellopy
  namespace: default
spec:
  deployment:
    checksum: {}
    literal: ZnJvbSB0aW1lIGltcG9ydCBzbGVlcAoKZGVmIG1haW4oKToKICAgIHNsZWVwKDIwKQogICAgcmV0dXJuICJIZWxsbywgd29ybGQhXG4i
    type: literal
  environment:
    name: hellopy
    namespace: default
  source:
    checksum: {}
```
NOTE: Contents of python script used in package:
```python
from time import sleep

def main():
    sleep(20)
    return "Hello, world!\n"
```
3. Create function with the following manifest
```yaml
apiVersion: fission.io/v1
kind: Function
metadata:
  name: hellopy
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 4
      MinScale: 0
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 4
  environment:
    name: hellopy
    namespace: default
  functionTimeout: 28800
  idletimeout: 10
  onceOnly: true
  package:
    packageref:
      name: hellopy
      namespace: default
  requestsPerPod: 1
```
4.  Create HttpTrigger with the following manifest
```yaml
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: hellopy
  namespace: default
spec:
  functionref:
    name: hellopy
    type: name
  methods:
  - GET
  relativeurl: /hellopy
```
5. Call the hellopy function using curl:
```shell
curl router/hellopy
```

**Expected result**

```
Hello, world!
```

**Actual result**
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

[fission-dump_1723890453.zip](https://github.com/user-attachments/files/16644441/fission-dump_1723890453.zip)

**Additional context**

When function type is poolmgr, the idletimeout kicks in only after the response is sent, as is expected.
