### ISSUE TITLE
When calling a newdeploy function multiple times concurrently, irrespective of the function maxScale value, the newdeploy pods don't scale beyond 1

### ISSUE THREAD

**Issue by sharang-lyric** [fission/fission#2993]
**Fission/Kubernetes version**

<pre>
$ fission version v1.20.3
$ kubectl version v1.27.2
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Docker Desktop

**Describe the bug**

I have a "hello world" newdeploy function running a script that waits for 20 seconds before responding. The function has a maxScale value of 4. The expectation here is that as needed, the executor can scale the number of pods running the function up to 4. However, when I make multiple additional function calls while the first function call is running, the number of pods never goes beyond 1.

**To Reproduce**

1. Create environment with following manifest
```yaml
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: hellopy
  namespace: default
spec:
  poolsize: 0
  runtime:
    image: fission/python-env
    podspec:
      containers:
      - image: fission/python-env
        imagePullPolicy: Always
        name: hellopy
  version: 3
```
2. Create package with the following manifest
```yaml
apiVersion: fission.io/v1
kind: Package
metadata:
  name: hellopy
  namespace: default
spec:
  deployment:
    checksum: {}
    literal: ZnJvbSB0aW1lIGltcG9ydCBzbGVlcAoKZGVmIG1haW4oKToKICAgIHNsZWVwKDIwKQogICAgcmV0dXJuICJIZWxsbywgd29ybGQhXG4i
    type: literal
  environment:
    name: hellopy
    namespace: default
  source:
    checksum: {}
```
NOTE: Contents of python script used in package:
```python
from time import sleep

def main():
    sleep(20)
    return "Hello, world!\n"
```
3. Create function with the following manifest
```yaml
apiVersion: fission.io/v1
kind: Function
metadata:
  name: hellopy
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 4
      MinScale: 0
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 4
  environment:
    name: hellopy
    namespace: default
  functionTimeout: 28800
  idletimeout: 45
  onceOnly: true
  package:
    packageref:
      name: hellopy
      namespace: default
  requestsPerPod: 1
```
4.  Create HttpTrigger with the following manifest
```yaml
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: hellopy
  namespace: default
spec:
  functionref:
    name: hellopy
    type: name
  methods:
  - GET
  relativeurl: /hellopy
```
5. Call the hellopy function using curl:
```shell
curl router/hellopy
```
6. Immediately call the hellopy function using curl from another terminal window:
```shell
curl router/hellopy
```

**Expected result**

There should be 2 newdeploy pods running to serve the 2 requests that have been made

**Actual result**
Only 1 newdeploy pod runs, and it tries to serve both the requests.

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

[fission-dump_1723891948.zip](https://github.com/user-attachments/files/16644559/fission-dump_1723891948.zip)

**Additional context**

onceOnly is true, but it is ignored as the same pod serves both requests. Is onceOnly only applicable for type `poolmgr`?
