### ISSUE TITLE
Implementing ValidatingAdmissionPolicy

### ISSUE THREAD

**Issue by neha-Gupta1** [fission/fission#3035]
Currently, Fission uses validating admission webhooks for validating Custom Resources (CRs). This approach requires maintaining a separate webhook server, which adds complexity to the system.
### Proposed Change
Replace the current validating admission webhook with ValidatingAdmissionPolicy for each CR in Fission. This change will simplify the architecture by eliminating the need for a separate webhook server for Validation.

### Implementation Details
1. **Create ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding**
For each CR in Fission, we will create a corresponding ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding. We'll start with the Fission Environment CR as a proof of concept.

Policy example with CEL for Environment CR: 
https://gist.github.com/neha-Gupta1/57b28e8c0fdf48340898e6f0f07668e1

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "validate-fission-environment"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["fission.io"]
      apiVersions: ["v1"]
      resources:   ["environments"]
      operations:  ["CREATE", "UPDATE"]
  validations:
    # Validations for metadata.name, metadata.namespace, spec.version, etc.
    # (as provided in the sample policy)

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "fission-environment-policy-binding"
spec:
  policyName: "validate-fission-environment"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchLabels:
        environment: fission
```
2. **CEL introduction**
Common Expression Language (CEL) was introduced into Kubernetes in version 1.25, which was released in August 2022. CEL provides a mechanism for evaluating complex validation rules in a simple, expressive way, enabling users to define validation logic directly in Kubernetes resources. CEL itself was developed by Google and is used in various Google APIs, designed for high-performance, safe expression evaluation.

We can use - https://playcel.undistro.io/ for validating CELs.

3. **Implement Validation Rules Using CEL**
We will rewrite all existing validation rules using Common Expression Language (CEL). CEL has almost basic functionalities like checking for all elements in a list, getting size of string and so on. Almost all the things which we are currently doing in the Validation webhook server seems to be possible with CEL.

4. **Testing**
- End-to-end tests to verify the entire validation process

### Challenges and Considerations

- What CEL can’t take care of-

Cross resource check. Checks like - don’t create a ‘function’ if ‘environment’ is not present don’t seem to be feasible here. But I don’t see any such thing currently implemented in the Validation as of now. 

- Reusing CEL - I could not find anything like - until function creation. So that the same verification can be used again and again. Eg, the valid string check in name and namespace.  

- Kubernetes Version Compatibility- The Validation admission Policy was marked as stable in Kubernetes v1.30. The Mutating admission Policy is still in plan for 1.32.

### Implementation Plan
We will need to introduce the ValidatingAdmissionPolicy in phases. Since the Mutating Admission Policy is still not in place we can’t remove the webhook server. But we can turn off the validation on the webhook side using a flag which would save some calls to the external server.

**Phase 1:**

- Implement feature flags for environment webhooks.
- Create Policies for the environment- Since it's a top level entity there would be less dependencies. And we will get a basic CEL prepared.
- Create the policies as part of installation. 
- Turn off validation webhook for env.

**Phase 2:** 

- Implement the same for ‘package’ and ‘triggers’.
- Create flags and set them properly.

**Phase 3:** 

- Make a ‘function’ policy. Make the flags as required.

**Phase 4:**

- Look at mutating webhooks. If they could be replaced by the new policy.
