### ISSUE TITLE
storagesvc start failed

### ISSUE THREAD

**Issue by cyxr001** [fission/fission#3050]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2024-10-04T07:43:36Z"
    GitCommit: 352090d0
    Version: v1.20.5
server:
  fission/core:
    BuildDate: "2024-10-04T07:43:36Z"
    GitCommit: 352090d0
    Version: v1.20.5

$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

I tried to remove the installation many times.

installation document is https://fission.io/docs/installation,  the comand like this:
```
export FISSION_NAMESPACE="fission"
kubectl create namespace $FISSION_NAMESPACE
kubectl create -k "github.com/fission/fission/crds/v1?ref=v1.20.5"
helm repo add fission-charts https://fission.github.io/fission-charts/
helm repo update
helm install --version v1.20.5 --namespace $FISSION_NAMESPACE fission fission-charts/fission-all
```
the list comand install output is :
```
W1028 14:14:58.552648  261800 warnings.go:70] metadata.name: this is used in Pod names and hostnames, which can result in surprising behavior; a DNS label is recommended: [must not contain dots]
NAME: fission
LAST DEPLOYED: Mon Oct 28 14:14:55 2024
NAMESPACE: fission
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Install the client CLI.

Mac:
  $ curl -Lo fission https://github.com/fission/fission/releases/download/v1.20.5/fission-v1.20.5-darwin-amd64 && chmod +x fission && sudo mv fission /usr/local/bin/

Linux:
  $ curl -Lo fission https://github.com/fission/fission/releases/download/v1.20.5/fission-v1.20.5-linux-amd64 && chmod +x fission && sudo mv fission /usr/local/bin/

Windows:
  For Windows, you can use the linux binary on WSL. Or you can download this windows executable: https://github.com/fission/fission/releases/download/v1.20.5/fission-v1.20.5-windows-amd64.exe

2. You're ready to use Fission!
  You can create fission resources in the namespace "default"

  # Create an environment
  $ fission env create --name nodejs --image fission/node-env --namespace default

  # Get a hello world
  $ curl https://raw.githubusercontent.com/fission/examples/master/nodejs/hello.js > hello.js

  # Register this function with Fission
  $ fission function create --name hello --env nodejs --code hello.js --namespace default

  # Run this function
  $ fission function test --name hello --namespace default
  Hello, world!
```
then I try to test nodejs , it succeed. but when I use go, it failed. 

I found it maybe because storagesvc is bad. I run the `fission check`
```
fission-services
--------------------
√ executor is running fine
√ router is running fine
× storagesvc deployment is not running
√ webhook is running fine

fission-version
--------------------
√ fission is up-to-date
```
Then, I kubectl describe the storagesvc pod, the error is 
```
 Warning  FailedScheduling  4m26s (x3 over 14m)  default-scheduler  0/2 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
```
this is releate pv and pvc problem.
I run the `kubectl get pvc -n fission`,  can see the fission-storage-pvc is pending.
```
 Normal  FailedBinding  3m22s (x62 over 18m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

Then I create a pv, the pvc can bound to the pv

**Expected result**
how could I modify the pv to dvp when I deploy?

**Additional context**
Another problem , everytime I install by helm, and the output name is fission.
but when I uninstall the fission, I cannot use `helm uninstall fission`, it reports `Error: uninstall: Release not loaded: fission: release: not found`. and there is no any output when I run helm list.

so everytime I want to uninstall, I delete the fission namespace directly  and delete crds stuffix with 'fission.io'. Is it ok ?

**Comment by soharab-ic** [comment]
- For dynamic volume provisioning, set `storageClass` in [values.yaml](https://github.com/fission/fission-charts/blob/main/charts/fission-all/values.yaml#L589).
- To uninstall fission, mention namespace too.
```
$ helm uninstall fission -n fission
```

**Comment by cyxr001** [comment]
@soharab-ic Thanks for your response,  add `-n fission` namespace I can see the installed fission. I think can add the explanation in the document https://fission.io/docs/installation/uninstallation/

After testing it, I have another question to want to  ask.
I try to add some tolerations in the podspec refer to https://fission.io/docs/usage/spec/podspec/toleration/
when I run `fission spec apply --wait`
but it report the `error applying specs: environment apply failed: Environment.fission.io "nodejs" is invalid: spec.runtime.podspec.containers: Required value`
what containers value should I set ?

**Comment by soharab-ic** [comment]
Sure @cyxr001, will update the document https://fission.io/docs/installation/uninstallation/
- This is how a generated environment spec looks like:
```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: go
spec:
  builder:
    command: build
    container:
      name: ""
      resources: {}
    image: ghcr.io/fission/go-builder
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    container:
      name: ""
      resources: {}
    image: ghcr.io/fission/go-env
  version: 3
```
- `containers` is a required field in podSpec, add tolerations like this. 
- The runtime container name should be equal to the environment name. Add a container to the `spec.runtime.podspec.containers` and it should be similar to the `spe.runtime.container`. For more info, take a look at this PR https://github.com/fission/fission/pull/3033
```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: go
spec:
  builder:
    command: build
    container:
      name: ""
      resources: {}
    image: ghcr.io/fission/go-builder
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    container:
      name: "go"
      resources: {}
    image: ghcr.io/fission/go-env
    podSpec:
      containers:
      - name: "go"
        resources: {}
      tolerations:
      - key: "reservation"
        operator: "Equal"
        value: "fission"
        effect: "NoSchedule"
  version: 3
```

- `--code` is used for single file source code which does not require additional building steps like compilation or dependency download. It can be used for lanuages like Python and NodeJS.
- `--src` flag can take a single source file , zip file or URL as source code. When creating a env, we set `--builder` flag with builder image, this image is used to compile the src code and generate the binary.
- `fission pkg getsrc --name aago-xxxx` download the source as zip file. Save the file as `.zip` extension and unzip it to get the src code.
