### ISSUE TITLE
 java client or rest api for java project

### ISSUE THREAD

**Issue by rain-lyy** [fission/fission#3063]
Hello dear fission team.
I'm currently working on a project written in java spring boot.
 I want to connect to fission which version is 1.20.5 and submit some functions from this java project.
But I find fission controller is removed from version 1.20.0.
Is there any other solutions available for java project connect to fission?

**Comment by bigbird-0101** [comment]
Currently, it creates resources through the kubernetes api. You can create them through the general resource api.

**Comment by rain-lyy** [comment]
I am a new user of Fission and I am not quite familiar with the resource creation of Fission. Could you give an example to illustrate how to create resources through the kubernetes api?
If I want to create a function, what resources do I need to create through the kubernetes api?

**Comment by sanketsudake** [comment]
@bigbird-0101's answer above is the right one, and it is worth spelling out with an example since
this comes up regularly.

**There is no REST API to target, by design.** The standalone Fission controller was removed in 1.20
precisely because it duplicated the Kubernetes API. Everything Fission manages is a CRD in the
`fission.io/v1` group, so *the Kubernetes API is the API*. The `fission` CLI itself is a client of it —
it creates and updates these CRs through a generated clientset and the controllers in
`fission-bundle` reconcile them. Anything the CLI can do, your Spring Boot service can do the same way.

From Java, use any Kubernetes client (the Fabric8 client or the official `kubernetes-client/java`)
with a custom-resource API. The objects you need for a function are an `Environment`, a `Package`,
and a `Function` referencing both:

```yaml
apiVersion: fission.io/v1
kind: Function
metadata:
  name: nodehello
  namespace: default
spec:
  environment:
    name: nodejs
    namespace: default
  package:
    packageref:
      name: hello-js-vm2y
      namespace: default
  InvokeStrategy:
    StrategyType: execution
    ExecutionStrategy:
      ExecutorType: newdeploy
      MinScale: 1
      MaxScale: 3
      TargetCPUPercent: 80
```

Add an `HTTPTrigger` to expose it over HTTP. The full schemas are in `crds/v1/` in this repo, so
`kubectl explain function.spec` works and any client that reads OpenAPI can generate types from them.

Two things that make this easier than it was when this issue was filed:

- **Packages no longer require an imperative upload.** A package can reference an OCI image built in
  your own CI, so there is no CLI-only step left in the path — the whole object graph is plain YAML
  you can apply from Java, Argo, Flux or Terraform.
- `docs/examples/terraform/` has a worked declarative example if you would rather manage these
  objects from IaC than from application code.

To set expectations: there is no maintained Java SDK for Fission, and none is planned — a Kubernetes
client against the CRDs above is the supported path.

@rain-lyy — hope the example answers your follow-up too. Closing as answered; open a new issue if you
hit something specific from the Java side.
