### ISSUE TITLE
Report some bugs about graceful exit, storage, buildcmd, executor

### ISSUE THREAD

**Issue by cyxr001** [fission/fission#3120]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2024-10-04T07:43:36Z"
    GitCommit: 352090d0
    Version: v1.20.5
server:
  fission/core:
    BuildDate: "2024-10-04T07:43:36Z"
    GitCommit: 352090d0
    Version: v1.20.5

$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
</pre>

**Describe the bug**
**1. the graceful exit problem**
when I create a env , and use `--graceperiod 90` set the pod graceful exit time, It doesn't work as expected. When I set the param, it will set env deployment :
```
terminationGracePeriodSeconds: 90
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sleep
          - "90"
```
When I update the env image, it will terminate the old pods, and the pods will exec the `/bin/sleep 90` preStop first, but the all grace time is 90s. The sigterm will be sent to env application after sleep 90, and the env http application has no time to do anything after receiving k8s the sigterm. Because it reached the 90s deadline.

why fission set the sleep preStop ?

Another problem in graceful exit is when I use the python env. 
python env registered to monitor the sigterm and sigint , but it won't be exit after received the sigterm.
https://github.com/fission/environments/blob/master/python/server.py#L64

For verifying it. I enter into the python env container, and send `kill -15 1` (1 is the pid `python3 server.py`). 
I can get the log `INFO - Received signal Terminated` (it generated by the flask signal_handler funciton), but the process won't exit and I can see the process still. 

Then I edit the env deployment, and make the sleep 90 to 10 ,but gracetime also is 90.  
The log (`INFO - Received signal Terminated`) can be seen after 10s, but the pods also cannot exit immediately. 

I think this is the python or flask problem?  I'm not very familiar with python, is there any way to solve it?

**2. minio storage url is not correct**
From the helm config, we can see minio is supported as the storage. https://github.com/fission/fission/blob/v1.20.5/charts/fission-all/values.yaml#L574

If the code size is more then  ArchiveLiteralSizeLimit(256 * 1024), it will upload the source code to the storage. But the download url that will store in the the package crd is not correct. 
minio also use s3 type, but the download url joined with s3.amazonaws domain. 
https://github.com/fission/fission/blob/v1.20.5/pkg/fission-cli/cmd/package/util/util.go#L116

The bucket is get from the storage component, I think the download url or endpoint also can get from storage component .

**3. package create buildcmd problem**
I upload source code with a zip package, and want to use the myself build.sh and add some param to the build.sh. But it cannot be recognized . like this:
fission package create --env mygo  --buildcmd "./build.sh abcd" ......
from the package crd we can see
```
spec:
  buildcmd: ./build.sh abcd
```

but it report the error:
```
error building source package: error starting cmd: exec: "build.sh abcd": executable file not found in $PATH
Error building deployment package: Internal error - 500 Internal Server Error
```
It seems regarding the "./build.sh abcd" as a the entire command.

for the builder.go https://github.com/fission/fission/blob/v1.20.5/pkg/builder/builder.go#L136
we can see the command should be splited `./build.sh` and `abcd`, but it doesn't work. 
From the builder log, also can see it:
```
{"level":"error","ts":"2024-12-25T08:43:14.269Z","logger":"builder","caller":"builder/builder.go:130","msg":"error building source package","error":"error starting cmd: exec: \"./build.sh abcd\": executable file not found in $PATH","errorVerbose":"exec: \"./build.sh abcd\": executable file not found in $PATH\nerror starting cmd\ngithub.com/fission/fission/pkg/builder.(*Builder).build\n\t/go/src/github.com/fission/fission/pkg/builder/builder.go:208\ngithub.com/fission/fission/pkg/builder.(*Builder).Handler\n\t/go/src/github.com/fission/fission/pkg/builder/builder.go:127\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2417\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1925\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374","stacktrace":"github.com/fission/fission/pkg/builder.(*Builder).Handler\n\t/go/src/github.com/fission/fission/pkg/builder/builder.go:130\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2417\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1925"}
```

I want to know why the builder doesn't work the split.

**4. env node selector stuck**
I code a env yaml, want to schedule the pod to node with label `test: ok`.
(the yaml does not use the `fission spec init` command yaml , because generated yaml applying will report container field error. I search the fission github to find the lastest yaml)
```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: go4
  namespace: ff
spec:
  builder:
    command: build
    container:
      name: ""
      resources: {}
    podspec:
      containers:
      - name: "builder"
        resources: {}
      nodeSelector:
        test: ok
    image: fission/go-builder-1.16
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    container:
      name: "go4"
      resources: {}
    podSpec:
      containers:
      - name: "go4"
        resources: {}
      nodeSelector:
        test: ok
    image: fission/go-env-1.16
  version: 3
```
After I fission spec apply it, the builder pod created(has deployment operator), but the env pods is not created. (and cannot find corresponding env deployment operator). kubectl get events also cannot see env deployment create.

In this time, my previous normal functions will get stuck when triggered now until it times out.

But when I restart the executor pod, the go4 env pods and deployment created successful, and the previous function also is to be normal.

I think it may be that the executor is stuck somewhere, which affects many places...
