### ISSUE TITLE
Duplicate Job names in helm chart templates

### ISSUE THREAD

**Issue by codecooper** [fission/fission#3127]
**Describe the bug**
There is a bug with the helm chart templates for jobs at `charts/fission-all/templates/analytics`. The Jobs are `post-upgrade-job.yaml` and `post-install-job.yaml`.

Both of the files are described using the following:

```yaml
{{- if .Values.analytics }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-{{ .Chart.Version }}
```

In the helm values, if analytics are `true` (which is the default), both jobs will try to be created and cause a conflict within helm. If I set `analytics` to false, the chart will install with the default values.

**Resolution**

Would it be possible to change the name to 

```yaml
name: {{ template "fullname" . }}-{{ .Chart.Version }}-{{ randNumeric 3 }}` 
```

or

```yaml
name: {{ template "fullname" . }}-{{ .Chart.Version }}-post-upgrade` 
```
