### ISSUE TITLE
Can not reapply specs containing HttpTrigger - false positive duplicate detection

### ISSUE THREAD

**Issue by ProjectMoon** [fission/fission#3153]
This is a re-filing of #2658 since I cannot reopen that issue.

**Fission/Kubernetes version**

Fission: 1.20.5
Kubernetes: Minikube 1.34.0

**Kubernetes platform (e.g. Google Kubernetes Engine)** Minikube

**Describe the bug**
When using `fission spec apply`, route specs with multiple HTTP methods cause the `fission` CLI to detect a duplicate, and deployment fails. I have to delete the routes every time I deploy.

My hunch is that it is caused by the multiple HTTP methods, as I only started noticing this when  I added `OPTIONS` in addition to `GET` or `POST` in the spec.

**To Reproduce**

A spec like this should cause the error:

```yaml
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: tasks-create
spec:
  createingress: false
  functionref:
    functionweights: null
    name: create-task
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /tasks/create
    tls: ""
  method: ""
  methods:
  - POST
  - OPTIONS
  prefix: ""
  relativeurl: /tasks/create

```

**Expected result**
Spec apply works fine.

**Actual result**

Spec apply fails with the error that a route with the same name/method/etc already exists.
