### ISSUE TITLE
Option to Mount Fission Router `feature-config` Without `subPath`

### ISSUE THREAD

**Issue by flip111** [fission/fission#3225]
The Fission router pod sometimes fails to start on my setup. It gets a `CreateContainerConfigError`. The error message says "mkdir ... file exists" when trying to set up the `config.yaml` from the `feature-config` ConfigMap using `subPath`. This seems to happen because old, locked files or mounts from previous router pods are not getting cleaned up properly by Kubernetes on the host node.

My setup is a single-node k0s cluster on NixOS. I'm trying to automate Fission installation with a script. When the router pod fails, my script tries to delete the pod, and then Kubernetes tries to make a new one. But the new one often hits the same "file exists" problem, likely because the underlying host path (something like `/var/lib/k0s/kubelet/pods/<OLD_POD_UID>/volume-subpaths/config-volume/router/0`) is still stuck from a previous attempt. My script tries hard to clean these old paths with `lsof`, `fuser`, `umount -l -f`, and even k0s service restarts and full `k0s reset`, but these stuck `.../router/0` paths are very hard to remove and often report "Device or resource busy."

If the Fission router Helm chart had an option to mount the `feature-config` ConfigMap *without* using `subPath`, this might help. For example, instead of using `subPath: config.yaml` to mount just one file, we could mount the entire `feature-config` ConfigMap into a directory like `/etc/fission-router-config/`. Then, the Fission router binary would need to be told to look for its configuration file at `/etc/fission-router-config/config.yaml` (or whatever the key name is in the ConfigMap).

This would simplify things because mounting an entire ConfigMap as a directory is often more robust and less prone to these tricky `subPath` cleanup issues that seem to happen on some systems or with certain container runtimes/kubelet versions. It avoids Kubernetes having to manage a specific file bind-mount inside the pod's volume directory structure on the host.

I think this could be useful for other people too. If anyone else runs into similar `subPath` issues with the router's config on different Kubernetes setups or host OSes, having an alternative mounting strategy would give them a way to work around it and get Fission router running more reliably. It makes Fission deployment more flexible.

Here's how I imagine it could work:

The Fission Helm chart could have a new value, maybe something like `router.config.mountAsFullDirectory: true` (defaulting to `false` to keep current behavior).

If `true`, the router deployment manifest would change from:
```yaml
# Current (simplified)
volumeMounts:
- name: config-volume
  mountPath: /etc/config/config.yaml # Mounts just the file
  subPath: config.yaml
volumes:
- name: config-volume
  configMap:
    name: feature-config
```

To something like:
```yaml
# Proposed (simplified)
volumeMounts:
- name: config-volume
  mountPath: /etc/fission-router-config # Mounts the whole ConfigMap here
volumes:
- name: config-volume
  configMap:
    name: feature-config
```
And then the Fission router binary inside the pod would need to know to read its configuration from `/etc/fission-router-config/config.yaml`. This might need an environment variable or a command-line argument for the router process, like `ROUTER_CONFIG_PATH=/etc/fission-router-config/config.yaml`.

This change would make the router less likely to fail due to these specific `subPath` and host-level file locking problems i'm seeing.

Thanks for looking into this.
