### ISSUE TITLE
Expose S3 config settings in storage service and helm chart

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#576]
Storage service uses a library that supports S3, but we currently only use its local volume feature.

This bug tracks:
 * [ ] exposing a flag to configure the storage system type
 * [ ] configuring S3 API endpoint
 * [ ] configuring S3 credentials
 * [ ] adding this to the helm chart

**Comment by pulberg** [comment]
Still waiting for this...

**Comment by vishal-biyani** [comment]
Hi, @pulberg Thanks for letting us know. We will prioritize this for an upcoming release.

**Comment by rajalokan** [comment]
I'm starting implementation for this. Before I go ahead with actual implementation, wanted to get a quick review from maintainers. 

Essentially this needs three bits. 
1. Handling S3 Persistence config in helm. 
2. Modify `fission-bundle` binary to handle `runStorageSvc` with S3 storage type. 
3. Adding more generic `StorageType` interface in `stowClient.go` 

### Handling S3 Persistence config in helm: 
- Introduce a new variable `storageType`. For our case it will be `storageType: s3`. 
- Based on the value of it, additional config option will be required. One sample example is 
```
persistence:
  enabled: true
  storageType: s3
  
  s3:
    endpoint: X.amazonaws.com
    configAccessKeyId: XXXX
    configSecretAccessKey: XXX
    configRegion: XXX
```

### Modify `fission-bundle` binary to handle `runStorageSvc` with S3 storage type.
- Can be done by adding one more else if condition in `fission-bundle/main.go`. This will be hooked to a new function `runS3StorageSvc()`

### Adding more generic `StorageType` interface in `stowClient.go` 
- Presently `StorageType` is a string. Proposing to conver this to interface. 
- Introduce two new structs `LocalStorageType` and `S3StorageType`.  With this dialing logic will be handled by corresponding items. 

Please review and see if this can be a conflict or potential issues?

**Comment by vishal-biyani** [comment]
Hey, @rajalokan Thanks - overall this looks really good. One thing I would like to do before we start implementation is to design the storage type struct etc. - as it is core to the configuration being passed and will affect the overall design. Can we take a stab at it here and once closed - we are good to start implementation.

**Comment by pulberg** [comment]
Another thing to consider, S3 does not always mean "AWS", there are many storage arrays that provide S3 functionality.  In my case, we are using EMC ECS, and will soon be using Pure Storage arrays that have S3 functionality.

I am also in a high-security environment that requires us to be much more specific in our configurations in order to prove limited scope during an audit. In order to support this, please make all available config vars editable by the user, and allow for addition configuration if needed, here is an example for my use-case:

```
s3:
  endpoint: some.url.here
  endpointPort: <need to be able to specify port>
  bucketName: <need to specify bucket name>
  folderName: <need to be able to specify a folder in the bucket>
  configAccessKeyId: XXXX
  configSecretAccessKey: XXX
  configRegion: <allowed to be blank on systems that do not have\support region info>
```

Thanks for working on this.

Phillip
