### ISSUE TITLE
Function logs not present in fn log command

### ISSUE THREAD

**Issue by life1347** [fission/fission#648]
If requests come to the router, the router will try to get a pod IP from executor to serve the request. Pool manager randomly chooses a pod from env pool, relabel it and reply pod IP. 
```
|requests| -> |router| -> |executor(pool manager)| -> |function pod|
```
The function logs generated by pods will be collected by `logger(fluentd)` and forward to influxdb to store.

A fluentd plugin called `kubernetes_metadata` will attach pods labels to function logs.

```
  labels:
    executorInstanceId: 2npeidlq
    functionName: python-hello-1524726464
    functionUid: 850adb77-4920-11e8-9e80-42010af001c5
    unmanaged: "true"
```
In this way we can find logs in db by `functionUid`.

However, if the duration between relabeling and log generating is too short, then the fluentd plugin may not have enough time to retrieve latest pod labels and cause logs lost. 

Also, another problem is that the wathcer inside plugin stop watching pods after some time. (https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/28)

We need to figure a better way to solve it.
