### ISSUE TITLE
Allow filing general runtime parameters to fission config spec

### ISSUE THREAD

**Issue by xiekeyang** [fission/fission#770]
Now env creation are including more and more general parameters, like version, resource limit, pool size, period… 

Current spec allow to file only little items like env name, base image of builder and runtime, or so, like [specs/env.yaml](https://github.com/fission/fission/blob/master/examples/spec-example/specs/env.yaml).

We may want to improve the config spec, as to allow configuration of detailed parameters like above mentioned:

Config spec may like:

```yaml
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: python
  namespace: default
spec:
  version: 2
  builder:
    command: build
    image: fission/python-builder
  runtime:
    image: fission/python-env
    poolsize: 3
    lifecycle:
      preStop:
        exec:
          command:
          - sleep
          - "5"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    env:
     - name: foo
        value: bar
```

Also, it may be the goal for other fission resources like function, package, specific CRD, or so.

Any thought?
